// js/cards-data.js
// Static 630-card checklist for Panini Adrenalyn XL FIFA World Cup 2026.
// Do not edit manually — this is the canonical data source.

export const CARDS = [
  // ── Golden Ballers (1–9) ────────────────────────────────────────────────
  { id: 1,   playerName: "Lionel Messi",       country: "Argentina",      cardType: "Golden Baller" },
  { id: 2,   playerName: "Vinícius Júnior",    country: "Brazil",         cardType: "Golden Baller" },
  { id: 3,   playerName: "Mohamed Salah",      country: "Egypt",          cardType: "Golden Baller" },
  { id: 4,   playerName: "Harry Kane",         country: "England",        cardType: "Golden Baller" },
  { id: 5,   playerName: "Kylian Mbappé",      country: "France",         cardType: "Golden Baller" },
  { id: 6,   playerName: "Son Heung-Min",      country: "Korea Republic", cardType: "Golden Baller" },
  { id: 7,   playerName: "Erling Haaland",     country: "Norway",         cardType: "Golden Baller" },
  { id: 8,   playerName: "Cristiano Ronaldo",  country: "Portugal",       cardType: "Golden Baller" },
  { id: 9,   playerName: "Lamine Yamal",       country: "Spain",          cardType: "Golden Baller" },

  // ── Algeria (10–21) ─────────────────────────────────────────────────────
  { id: 10,  playerName: "Rayan Aït-Nouri",    country: "Algeria",        cardType: "Fan Favourite" },
  { id: 11,  playerName: "Team Logo",          country: "Algeria",        cardType: "Team Logo" },
  { id: 12,  playerName: "Riyad Mahrez",       country: "Algeria",        cardType: "Icon" },
  { id: 13,  playerName: "Alexis Guendouz",    country: "Algeria",        cardType: "Hero" },
  { id: 14,  playerName: "Ramy Bensebaini",    country: "Algeria",        cardType: "Hero" },
  { id: 15,  playerName: "Youcef Atal",        country: "Algeria",        cardType: "Hero" },
  { id: 16,  playerName: "Aïssa Mandi",        country: "Algeria",        cardType: "Hero" },
  { id: 17,  playerName: "Nabil Bentaleb",     country: "Algeria",        cardType: "Hero" },
  { id: 18,  playerName: "Saïd Benrahma",      country: "Algeria",        cardType: "Hero" },
  { id: 19,  playerName: "Amine Gouiri",       country: "Algeria",        cardType: "Hero" },
  { id: 20,  playerName: "Mohammed Amoura",    country: "Algeria",        cardType: "Hero" },
  { id: 21,  playerName: "Baghdad Bounedjah",  country: "Algeria",        cardType: "Hero" },

  // ── Argentina (22–33) ───────────────────────────────────────────────────
  { id: 22,  playerName: "Julián Álvarez",     country: "Argentina",      cardType: "Fan Favourite" },
  { id: 23,  playerName: "Team Logo",          country: "Argentina",      cardType: "Team Logo" },
  { id: 24,  playerName: "Lionel Messi",       country: "Argentina",      cardType: "Icon" },
  { id: 25,  playerName: "Emiliano Martínez",  country: "Argentina",      cardType: "Hero" },
  { id: 26,  playerName: "Nahuel Molina",      country: "Argentina",      cardType: "Hero" },
  { id: 27,  playerName: "Cristian Romero",    country: "Argentina",      cardType: "Hero" },
  { id: 28,  playerName: "Nicolás Otamendi",   country: "Argentina",      cardType: "Hero" },
  { id: 29,  playerName: "Enzo Fernández",     country: "Argentina",      cardType: "Hero" },
  { id: 30,  playerName: "Alexis Mac Allister", country: "Argentina",     cardType: "Hero" },
  { id: 31,  playerName: "Rodrigo de Paul",    country: "Argentina",      cardType: "Hero" },
  { id: 32,  playerName: "Giuliano Simeone",   country: "Argentina",      cardType: "Hero" },
  { id: 33,  playerName: "Lautaro Martínez",   country: "Argentina",      cardType: "Hero" },

  // ── Australia (34–45) ───────────────────────────────────────────────────
  { id: 34,  playerName: "Harry Souttar",      country: "Australia",      cardType: "Fan Favourite" },
  { id: 35,  playerName: "Team Logo",          country: "Australia",      cardType: "Team Logo" },
  { id: 36,  playerName: "Mathew Ryan",        country: "Australia",      cardType: "Icon" },
  { id: 37,  playerName: "Alessandro Circati", country: "Australia",      cardType: "Hero" },
  { id: 38,  playerName: "Jordan Bos",         country: "Australia",      cardType: "Hero" },
  { id: 39,  playerName: "Lewis Miller",       country: "Australia",      cardType: "Hero" },
  { id: 40,  playerName: "Miloš Degenek",      country: "Australia",      cardType: "Hero" },
  { id: 41,  playerName: "Jackson Irvine",     country: "Australia",      cardType: "Hero" },
  { id: 42,  playerName: "Riley McGree",       country: "Australia",      cardType: "Hero" },
  { id: 43,  playerName: "Aiden O'Neill",      country: "Australia",      cardType: "Hero" },
  { id: 44,  playerName: "Connor Metcalfe",    country: "Australia",      cardType: "Hero" },
  { id: 45,  playerName: "Craig Goodwin",      country: "Australia",      cardType: "Hero" },

  // ── Austria (46–57) ─────────────────────────────────────────────────────
  { id: 46,  playerName: "Marko Arnautović",   country: "Austria",        cardType: "Fan Favourite" },
  { id: 47,  playerName: "Team Logo",          country: "Austria",        cardType: "Team Logo" },
  { id: 48,  playerName: "David Alaba",        country: "Austria",        cardType: "Icon" },
  { id: 49,  playerName: "Alexander Schlager", country: "Austria",        cardType: "Hero" },
  { id: 50,  playerName: "Kevin Danso",        country: "Austria",        cardType: "Hero" },
  { id: 51,  playerName: "Philipp Lienhart",   country: "Austria",        cardType: "Hero" },
  { id: 52,  playerName: "Konrad Laimer",      country: "Austria",        cardType: "Hero" },
  { id: 53,  playerName: "Nicolas Seiwald",    country: "Austria",        cardType: "Hero" },
  { id: 54,  playerName: "Marcel Sabitzer",    country: "Austria",        cardType: "Hero" },
  { id: 55,  playerName: "Florian Grillitsch", country: "Austria",        cardType: "Hero" },
  { id: 56,  playerName: "Christoph Baumgartner", country: "Austria",    cardType: "Hero" },
  { id: 57,  playerName: "Michael Gregoritsch", country: "Austria",       cardType: "Hero" },

  // ── Belgium (58–69) ─────────────────────────────────────────────────────
  { id: 58,  playerName: "Youri Tielemans",    country: "Belgium",        cardType: "Fan Favourite" },
  { id: 59,  playerName: "Team Logo",          country: "Belgium",        cardType: "Team Logo" },
  { id: 60,  playerName: "Kevin de Bruyne",    country: "Belgium",        cardType: "Icon" },
  { id: 61,  playerName: "Thibaut Courtois",   country: "Belgium",        cardType: "Hero" },
  { id: 62,  playerName: "Arthur Theate",      country: "Belgium",        cardType: "Hero" },
  { id: 63,  playerName: "Timothy Castagne",   country: "Belgium",        cardType: "Hero" },
  { id: 64,  playerName: "Maxim De Cuyper",    country: "Belgium",        cardType: "Hero" },
  { id: 65,  playerName: "Amadou Onana",       country: "Belgium",        cardType: "Hero" },
  { id: 66,  playerName: "Jérémy Doku",        country: "Belgium",        cardType: "Hero" },
  { id: 67,  playerName: "Charles de Ketelaere", country: "Belgium",      cardType: "Hero" },
  { id: 68,  playerName: "Leandro Trossard",   country: "Belgium",        cardType: "Hero" },
  { id: 69,  playerName: "Romelu Lukaku",      country: "Belgium",        cardType: "Hero" },

  // ── Brazil (70–81) ──────────────────────────────────────────────────────
  { id: 70,  playerName: "Marquinhos",         country: "Brazil",         cardType: "Fan Favourite" },
  { id: 71,  playerName: "Team Logo",          country: "Brazil",         cardType: "Team Logo" },
  { id: 72,  playerName: "Vinícius Júnior",    country: "Brazil",         cardType: "Icon" },
  { id: 73,  playerName: "Alisson",            country: "Brazil",         cardType: "Hero" },
  { id: 74,  playerName: "Danilo",             country: "Brazil",         cardType: "Hero" },
  { id: 75,  playerName: "Éder Militão",       country: "Brazil",         cardType: "Hero" },
  { id: 76,  playerName: "Gabriel Magalhães",  country: "Brazil",         cardType: "Hero" },
  { id: 77,  playerName: "Casemiro",           country: "Brazil",         cardType: "Hero" },
  { id: 78,  playerName: "Bruno Guimaraes",    country: "Brazil",         cardType: "Hero" },
  { id: 79,  playerName: "Rodrygo",            country: "Brazil",         cardType: "Hero" },
  { id: 80,  playerName: "Matheus Cunha",      country: "Brazil",         cardType: "Hero" },
  { id: 81,  playerName: "Raphinha",           country: "Brazil",         cardType: "Hero" },

  // ── Canada (82–93) ──────────────────────────────────────────────────────
  { id: 82,  playerName: "Jonathan David",     country: "Canada",         cardType: "Fan Favourite" },
  { id: 83,  playerName: "Team Logo",          country: "Canada",         cardType: "Team Logo" },
  { id: 84,  playerName: "Alphonso Davies",    country: "Canada",         cardType: "Icon" },
  { id: 85,  playerName: "Dayne St. Clair",    country: "Canada",         cardType: "Hero" },
  { id: 86,  playerName: "Richie Laryea",      country: "Canada",         cardType: "Hero" },
  { id: 87,  playerName: "Derek Cornelius",    country: "Canada",         cardType: "Hero" },
  { id: 88,  playerName: "Stephen Eustaquio",  country: "Canada",         cardType: "Hero" },
  { id: 89,  playerName: "Ismaël Koné",        country: "Canada",         cardType: "Hero" },
  { id: 90,  playerName: "Jonathan Osorio",    country: "Canada",         cardType: "Hero" },
  { id: 91,  playerName: "Jacob Shaffelburg",  country: "Canada",         cardType: "Hero" },
  { id: 92,  playerName: "Tajon Buchanan",     country: "Canada",         cardType: "Hero" },
  { id: 93,  playerName: "Cyle Larin",         country: "Canada",         cardType: "Hero" },

  // ── Cape Verde (94–105) ─────────────────────────────────────────────────
  { id: 94,  playerName: "Vozinha",            country: "Cape Verde",     cardType: "Fan Favourite" },
  { id: 95,  playerName: "Team Logo",          country: "Cape Verde",     cardType: "Team Logo" },
  { id: 96,  playerName: "Ryan Mendes",        country: "Cape Verde",     cardType: "Icon" },
  { id: 97,  playerName: "Logan Costa",        country: "Cape Verde",     cardType: "Hero" },
  { id: 98,  playerName: "Pico",               country: "Cape Verde",     cardType: "Hero" },
  { id: 99,  playerName: "Steven Moreira",     country: "Cape Verde",     cardType: "Hero" },
  { id: 100, playerName: "João Paulo",         country: "Cape Verde",     cardType: "Hero" },
  { id: 101, playerName: "Willy Semedo",       country: "Cape Verde",     cardType: "Hero" },
  { id: 102, playerName: "Jamiro Monteiro",    country: "Cape Verde",     cardType: "Hero" },
  { id: 103, playerName: "Kenny Rocha",        country: "Cape Verde",     cardType: "Hero" },
  { id: 104, playerName: "Garry Rodrigues",    country: "Cape Verde",     cardType: "Hero" },
  { id: 105, playerName: "Djaniny",            country: "Cape Verde",     cardType: "Hero" },

  // ── Colombia (106–117) ──────────────────────────────────────────────────
  { id: 106, playerName: "James Rodríguez",    country: "Colombia",       cardType: "Fan Favourite" },
  { id: 107, playerName: "Team Logo",          country: "Colombia",       cardType: "Team Logo" },
  { id: 108, playerName: "Luis Díaz",          country: "Colombia",       cardType: "Icon" },
  { id: 109, playerName: "Camilo Vargas",      country: "Colombia",       cardType: "Hero" },
  { id: 110, playerName: "Daniel Muñoz",       country: "Colombia",       cardType: "Hero" },
  { id: 111, playerName: "Yerry Mina",         country: "Colombia",       cardType: "Hero" },
  { id: 112, playerName: "Dávinson Sánchez",   country: "Colombia",       cardType: "Hero" },
  { id: 113, playerName: "Wilmar Barrios",     country: "Colombia",       cardType: "Hero" },
  { id: 114, playerName: "Richard Ríos",       country: "Colombia",       cardType: "Hero" },
  { id: 115, playerName: "Jhon Córdoba",       country: "Colombia",       cardType: "Hero" },
  { id: 116, playerName: "Rafael Santos Borré", country: "Colombia",      cardType: "Hero" },
  { id: 117, playerName: "Falcao García",      country: "Colombia",       cardType: "Hero" },

  // ── Costa Rica (118–129) ────────────────────────────────────────────────
  { id: 118, playerName: "Keylor Navas",       country: "Costa Rica",     cardType: "Fan Favourite" },
  { id: 119, playerName: "Team Logo",          country: "Costa Rica",     cardType: "Team Logo" },
  { id: 120, playerName: "Bryan Ruiz",         country: "Costa Rica",     cardType: "Icon" },
  { id: 121, playerName: "Patrick Sequeira",   country: "Costa Rica",     cardType: "Hero" },
  { id: 122, playerName: "Kendall Waston",     country: "Costa Rica",     cardType: "Hero" },
  { id: 123, playerName: "Oscar Duarte",       country: "Costa Rica",     cardType: "Hero" },
  { id: 124, playerName: "Francisco Calvo",    country: "Costa Rica",     cardType: "Hero" },
  { id: 125, playerName: "Celso Borges",       country: "Costa Rica",     cardType: "Hero" },
  { id: 126, playerName: "Yeltsin Tejeda",     country: "Costa Rica",     cardType: "Hero" },
  { id: 127, playerName: "Bryan Oviedo",       country: "Costa Rica",     cardType: "Hero" },
  { id: 128, playerName: "Joel Campbell",      country: "Costa Rica",     cardType: "Hero" },
  { id: 129, playerName: "Alonso Martínez",    country: "Costa Rica",     cardType: "Hero" },

  // ── Croatia (130–141) ───────────────────────────────────────────────────
  { id: 130, playerName: "Ivan Perišić",       country: "Croatia",        cardType: "Fan Favourite" },
  { id: 131, playerName: "Team Logo",          country: "Croatia",        cardType: "Team Logo" },
  { id: 132, playerName: "Luka Modrić",        country: "Croatia",        cardType: "Icon" },
  { id: 133, playerName: "Dominik Livaković",  country: "Croatia",        cardType: "Hero" },
  { id: 134, playerName: "Josip Juranović",    country: "Croatia",        cardType: "Hero" },
  { id: 135, playerName: "Joško Gvardiol",     country: "Croatia",        cardType: "Hero" },
  { id: 136, playerName: "Dejan Lovren",       country: "Croatia",        cardType: "Hero" },
  { id: 137, playerName: "Mateo Kovačić",      country: "Croatia",        cardType: "Hero" },
  { id: 138, playerName: "Marcelo Brozović",   country: "Croatia",        cardType: "Hero" },
  { id: 139, playerName: "Nikola Vlašić",      country: "Croatia",        cardType: "Hero" },
  { id: 140, playerName: "Andrej Kramarić",    country: "Croatia",        cardType: "Hero" },
  { id: 141, playerName: "Bruno Petković",     country: "Croatia",        cardType: "Hero" },

  // ── Ecuador (142–153) ───────────────────────────────────────────────────
  { id: 142, playerName: "Enner Valencia",     country: "Ecuador",        cardType: "Fan Favourite" },
  { id: 143, playerName: "Team Logo",          country: "Ecuador",        cardType: "Team Logo" },
  { id: 144, playerName: "Moisés Caicedo",     country: "Ecuador",        cardType: "Icon" },
  { id: 145, playerName: "Hernán Galíndez",    country: "Ecuador",        cardType: "Hero" },
  { id: 146, playerName: "Piero Hincapié",     country: "Ecuador",        cardType: "Hero" },
  { id: 147, playerName: "Félix Torres",       country: "Ecuador",        cardType: "Hero" },
  { id: 148, playerName: "Robert Arboleda",    country: "Ecuador",        cardType: "Hero" },
  { id: 149, playerName: "Angelo Preciado",    country: "Ecuador",        cardType: "Hero" },
  { id: 150, playerName: "Carlos Gruezo",      country: "Ecuador",        cardType: "Hero" },
  { id: 151, playerName: "Jeremy Sarmiento",   country: "Ecuador",        cardType: "Hero" },
  { id: 152, playerName: "Michael Estrada",    country: "Ecuador",        cardType: "Hero" },
  { id: 153, playerName: "Kevin Rodríguez",    country: "Ecuador",        cardType: "Hero" },

  // ── Egypt (154–165) ─────────────────────────────────────────────────────
  { id: 154, playerName: "Mohamed Salah",      country: "Egypt",          cardType: "Fan Favourite" },
  { id: 155, playerName: "Team Logo",          country: "Egypt",          cardType: "Team Logo" },
  { id: 156, playerName: "Ahmed El Shenawy",   country: "Egypt",          cardType: "Icon" },
  { id: 157, playerName: "Mohamed Abou Gabal", country: "Egypt",          cardType: "Hero" },
  { id: 158, playerName: "Ahmed Hegazi",       country: "Egypt",          cardType: "Hero" },
  { id: 159, playerName: "Omar Kamal",         country: "Egypt",          cardType: "Hero" },
  { id: 160, playerName: "Mostafa Mohamed",    country: "Egypt",          cardType: "Hero" },
  { id: 161, playerName: "Amr El Solia",       country: "Egypt",          cardType: "Hero" },
  { id: 162, playerName: "Emam Ashour",        country: "Egypt",          cardType: "Hero" },
  { id: 163, playerName: "Akram Tawfik",       country: "Egypt",          cardType: "Hero" },
  { id: 164, playerName: "Mahmoud Trezeguet",  country: "Egypt",          cardType: "Hero" },
  { id: 165, playerName: "Omar Marmoush",      country: "Egypt",          cardType: "Hero" },

  // ── England (166–177) ───────────────────────────────────────────────────
  { id: 166, playerName: "Bukayo Saka",        country: "England",        cardType: "Fan Favourite" },
  { id: 167, playerName: "Team Logo",          country: "England",        cardType: "Team Logo" },
  { id: 168, playerName: "Harry Kane",         country: "England",        cardType: "Icon" },
  { id: 169, playerName: "Jordan Pickford",    country: "England",        cardType: "Hero" },
  { id: 170, playerName: "Kyle Walker",        country: "England",        cardType: "Hero" },
  { id: 171, playerName: "John Stones",        country: "England",        cardType: "Hero" },
  { id: 172, playerName: "Marc Guéhi",         country: "England",        cardType: "Hero" },
  { id: 173, playerName: "Declan Rice",        country: "England",        cardType: "Hero" },
  { id: 174, playerName: "Jude Bellingham",    country: "England",        cardType: "Hero" },
  { id: 175, playerName: "Phil Foden",         country: "England",        cardType: "Hero" },
  { id: 176, playerName: "Marcus Rashford",    country: "England",        cardType: "Hero" },
  { id: 177, playerName: "Cole Palmer",        country: "England",        cardType: "Hero" },

  // ── France (178–189) ────────────────────────────────────────────────────
  { id: 178, playerName: "Antoine Griezmann",  country: "France",         cardType: "Fan Favourite" },
  { id: 179, playerName: "Team Logo",          country: "France",         cardType: "Team Logo" },
  { id: 180, playerName: "Kylian Mbappé",      country: "France",         cardType: "Icon" },
  { id: 181, playerName: "Mike Maignan",       country: "France",         cardType: "Hero" },
  { id: 182, playerName: "Benjamin Pavard",    country: "France",         cardType: "Hero" },
  { id: 183, playerName: "Raphaël Varane",     country: "France",         cardType: "Hero" },
  { id: 184, playerName: "Ibrahima Konaté",    country: "France",         cardType: "Hero" },
  { id: 185, playerName: "Aurélien Tchouaméni", country: "France",        cardType: "Hero" },
  { id: 186, playerName: "N'Golo Kanté",       country: "France",         cardType: "Hero" },
  { id: 187, playerName: "Eduardo Camavinga",  country: "France",         cardType: "Hero" },
  { id: 188, playerName: "Ousmane Dembélé",    country: "France",         cardType: "Hero" },
  { id: 189, playerName: "Marcus Thuram",      country: "France",         cardType: "Hero" },

  // ── Germany (190–201) ───────────────────────────────────────────────────
  { id: 190, playerName: "Thomas Müller",      country: "Germany",        cardType: "Fan Favourite" },
  { id: 191, playerName: "Team Logo",          country: "Germany",        cardType: "Team Logo" },
  { id: 192, playerName: "Manuel Neuer",       country: "Germany",        cardType: "Icon" },
  { id: 193, playerName: "Marc-André ter Stegen", country: "Germany",     cardType: "Hero" },
  { id: 194, playerName: "Joshua Kimmich",     country: "Germany",        cardType: "Hero" },
  { id: 195, playerName: "Antonio Rüdiger",    country: "Germany",        cardType: "Hero" },
  { id: 196, playerName: "Niklas Süle",        country: "Germany",        cardType: "Hero" },
  { id: 197, playerName: "Toni Kroos",         country: "Germany",        cardType: "Hero" },
  { id: 198, playerName: "Ilkay Gündogan",     country: "Germany",        cardType: "Hero" },
  { id: 199, playerName: "Kai Havertz",        country: "Germany",        cardType: "Hero" },
  { id: 200, playerName: "Florian Wirtz",      country: "Germany",        cardType: "Hero" },
  { id: 201, playerName: "Leroy Sané",         country: "Germany",        cardType: "Hero" },

  // ── Ghana (202–213) ─────────────────────────────────────────────────────
  { id: 202, playerName: "André Ayew",         country: "Ghana",          cardType: "Fan Favourite" },
  { id: 203, playerName: "Team Logo",          country: "Ghana",          cardType: "Team Logo" },
  { id: 204, playerName: "Thomas Partey",      country: "Ghana",          cardType: "Icon" },
  { id: 205, playerName: "Lawrence Ati-Zigi",  country: "Ghana",          cardType: "Hero" },
  { id: 206, playerName: "Daniel Amartey",     country: "Ghana",          cardType: "Hero" },
  { id: 207, playerName: "Alexander Djiku",    country: "Ghana",          cardType: "Hero" },
  { id: 208, playerName: "Tariq Lamptey",      country: "Ghana",          cardType: "Hero" },
  { id: 209, playerName: "Baba Rahman",        country: "Ghana",          cardType: "Hero" },
  { id: 210, playerName: "Jordan Ayew",        country: "Ghana",          cardType: "Hero" },
  { id: 211, playerName: "Mohammed Kudus",     country: "Ghana",          cardType: "Hero" },
  { id: 212, playerName: "Antoine Semenyo",    country: "Ghana",          cardType: "Hero" },
  { id: 213, playerName: "Inaki Williams",     country: "Ghana",          cardType: "Hero" },

  // ── Honduras (214–225) ──────────────────────────────────────────────────
  { id: 214, playerName: "Alberth Elis",       country: "Honduras",       cardType: "Fan Favourite" },
  { id: 215, playerName: "Team Logo",          country: "Honduras",       cardType: "Team Logo" },
  { id: 216, playerName: "Luis Palma",         country: "Honduras",       cardType: "Icon" },
  { id: 217, playerName: "Harold Fonseca",     country: "Honduras",       cardType: "Hero" },
  { id: 218, playerName: "Marcelo Santos",     country: "Honduras",       cardType: "Hero" },
  { id: 219, playerName: "Denil Maldonado",    country: "Honduras",       cardType: "Hero" },
  { id: 220, playerName: "Maynor Figueroa",    country: "Honduras",       cardType: "Hero" },
  { id: 221, playerName: "Deybi Flores",       country: "Honduras",       cardType: "Hero" },
  { id: 222, playerName: "Jonathan Rubio",     country: "Honduras",       cardType: "Hero" },
  { id: 223, playerName: "Romell Quioto",      country: "Honduras",       cardType: "Hero" },
  { id: 224, playerName: "Bryan Moya",         country: "Honduras",       cardType: "Hero" },
  { id: 225, playerName: "Rigoberto Rivas",    country: "Honduras",       cardType: "Hero" },

  // ── Iran (226–237) ──────────────────────────────────────────────────────
  { id: 226, playerName: "Mehdi Taremi",       country: "Iran",           cardType: "Fan Favourite" },
  { id: 227, playerName: "Team Logo",          country: "Iran",           cardType: "Team Logo" },
  { id: 228, playerName: "Alireza Jahanbakhsh", country: "Iran",          cardType: "Icon" },
  { id: 229, playerName: "Alireza Beiranvand",  country: "Iran",          cardType: "Hero" },
  { id: 230, playerName: "Shoja Khalilzadeh",  country: "Iran",           cardType: "Hero" },
  { id: 231, playerName: "Morteza Pouraliganji", country: "Iran",         cardType: "Hero" },
  { id: 232, playerName: "Majid Hosseini",     country: "Iran",           cardType: "Hero" },
  { id: 233, playerName: "Ahmad Noorollahi",   country: "Iran",           cardType: "Hero" },
  { id: 234, playerName: "Saeid Ezatolahi",    country: "Iran",           cardType: "Hero" },
  { id: 235, playerName: "Ali Gholizadeh",     country: "Iran",           cardType: "Hero" },
  { id: 236, playerName: "Sardar Azmoun",      country: "Iran",           cardType: "Hero" },
  { id: 237, playerName: "Karim Ansarifard",   country: "Iran",           cardType: "Hero" },

  // ── Japan (238–249) ─────────────────────────────────────────────────────
  { id: 238, playerName: "Takumi Minamino",    country: "Japan",          cardType: "Fan Favourite" },
  { id: 239, playerName: "Team Logo",          country: "Japan",          cardType: "Team Logo" },
  { id: 240, playerName: "Takefusa Kubo",      country: "Japan",          cardType: "Icon" },
  { id: 241, playerName: "Shuichi Gonda",      country: "Japan",          cardType: "Hero" },
  { id: 242, playerName: "Hiroki Sakai",       country: "Japan",          cardType: "Hero" },
  { id: 243, playerName: "Maya Yoshida",       country: "Japan",          cardType: "Hero" },
  { id: 244, playerName: "Ko Itakura",         country: "Japan",          cardType: "Hero" },
  { id: 245, playerName: "Wataru Endo",        country: "Japan",          cardType: "Hero" },
  { id: 246, playerName: "Hidemasa Morita",    country: "Japan",          cardType: "Hero" },
  { id: 247, playerName: "Junya Ito",          country: "Japan",          cardType: "Hero" },
  { id: 248, playerName: "Ritsu Doan",         country: "Japan",          cardType: "Hero" },
  { id: 249, playerName: "Daichi Kamada",      country: "Japan",          cardType: "Hero" },

  // ── Kenya (250–261) ─────────────────────────────────────────────────────
  { id: 250, playerName: "Michael Olunga",     country: "Kenya",          cardType: "Fan Favourite" },
  { id: 251, playerName: "Team Logo",          country: "Kenya",          cardType: "Team Logo" },
  { id: 252, playerName: "Victor Wanyama",     country: "Kenya",          cardType: "Icon" },
  { id: 253, playerName: "Patrick Matasi",     country: "Kenya",          cardType: "Hero" },
  { id: 254, playerName: "Brian Mandela",      country: "Kenya",          cardType: "Hero" },
  { id: 255, playerName: "Joash Onyango",      country: "Kenya",          cardType: "Hero" },
  { id: 256, playerName: "Joseph Okumu",       country: "Kenya",          cardType: "Hero" },
  { id: 257, playerName: "Anthony Akumu",      country: "Kenya",          cardType: "Hero" },
  { id: 258, playerName: "Kenneth Muguna",     country: "Kenya",          cardType: "Hero" },
  { id: 259, playerName: "Erick Johanna",      country: "Kenya",          cardType: "Hero" },
  { id: 260, playerName: "Ovella Ochieng",     country: "Kenya",          cardType: "Hero" },
  { id: 261, playerName: "John Avire",         country: "Kenya",          cardType: "Hero" },

  // ── Korea Republic (262–273) ────────────────────────────────────────────
  { id: 262, playerName: "Hwang Hee-Chan",     country: "Korea Republic", cardType: "Fan Favourite" },
  { id: 263, playerName: "Team Logo",          country: "Korea Republic", cardType: "Team Logo" },
  { id: 264, playerName: "Son Heung-Min",      country: "Korea Republic", cardType: "Icon" },
  { id: 265, playerName: "Kim Seung-Gyu",      country: "Korea Republic", cardType: "Hero" },
  { id: 266, playerName: "Kim Min-Jae",        country: "Korea Republic", cardType: "Hero" },
  { id: 267, playerName: "Kim Young-Gwon",     country: "Korea Republic", cardType: "Hero" },
  { id: 268, playerName: "Lee Ki-Je",          country: "Korea Republic", cardType: "Hero" },
  { id: 269, playerName: "Jung Woo-Young",     country: "Korea Republic", cardType: "Hero" },
  { id: 270, playerName: "Lee Jae-Sung",       country: "Korea Republic", cardType: "Hero" },
  { id: 271, playerName: "Hwang In-Beom",      country: "Korea Republic", cardType: "Hero" },
  { id: 272, playerName: "Cho Gue-Sung",       country: "Korea Republic", cardType: "Hero" },
  { id: 273, playerName: "Lee Kang-In",        country: "Korea Republic", cardType: "Hero" },

  // ── Malaysia (274–285) ──────────────────────────────────────────────────
  { id: 274, playerName: "Safawi Rasid",       country: "Malaysia",       cardType: "Fan Favourite" },
  { id: 275, playerName: "Team Logo",          country: "Malaysia",       cardType: "Team Logo" },
  { id: 276, playerName: "Mohd Faiz Subri",    country: "Malaysia",       cardType: "Icon" },
  { id: 277, playerName: "Khairulazhan Khalid", country: "Malaysia",      cardType: "Hero" },
  { id: 278, playerName: "Matthew Davies",     country: "Malaysia",       cardType: "Hero" },
  { id: 279, playerName: "Dominic Tan",        country: "Malaysia",       cardType: "Hero" },
  { id: 280, playerName: "La'Vere Corbin-Ong", country: "Malaysia",       cardType: "Hero" },
  { id: 281, playerName: "Arif Aiman Hanapi",  country: "Malaysia",       cardType: "Hero" },
  { id: 282, playerName: "Brendan Gan",        country: "Malaysia",       cardType: "Hero" },
  { id: 283, playerName: "Faisal Halim",       country: "Malaysia",       cardType: "Hero" },
  { id: 284, playerName: "Darren Lok",         country: "Malaysia",       cardType: "Hero" },
  { id: 285, playerName: "Mohamad Faisal",     country: "Malaysia",       cardType: "Hero" },

  // ── Mali (286–297) ──────────────────────────────────────────────────────
  { id: 286, playerName: "Moussa Marega",      country: "Mali",           cardType: "Fan Favourite" },
  { id: 287, playerName: "Team Logo",          country: "Mali",           cardType: "Team Logo" },
  { id: 288, playerName: "Yves Bissouma",      country: "Mali",           cardType: "Icon" },
  { id: 289, playerName: "Djigui Diarra",      country: "Mali",           cardType: "Hero" },
  { id: 290, playerName: "Hamari Traoré",      country: "Mali",           cardType: "Hero" },
  { id: 291, playerName: "Molla Wagué",        country: "Mali",           cardType: "Hero" },
  { id: 292, playerName: "Falaye Sacko",       country: "Mali",           cardType: "Hero" },
  { id: 293, playerName: "Diadie Samassekou",  country: "Mali",           cardType: "Hero" },
  { id: 294, playerName: "Lassana Coulibaly",  country: "Mali",           cardType: "Hero" },
  { id: 295, playerName: "Adama Traoré",       country: "Mali",           cardType: "Hero" },
  { id: 296, playerName: "El Bilal Touré",     country: "Mali",           cardType: "Hero" },
  { id: 297, playerName: "Ibrahima Koné",      country: "Mali",           cardType: "Hero" },

  // ── Mexico (298–309) ────────────────────────────────────────────────────
  { id: 298, playerName: "Hirving Lozano",     country: "Mexico",         cardType: "Fan Favourite" },
  { id: 299, playerName: "Team Logo",          country: "Mexico",         cardType: "Team Logo" },
  { id: 300, playerName: "Guillermo Ochoa",    country: "Mexico",         cardType: "Icon" },
  { id: 301, playerName: "Kevin Álvarez",      country: "Mexico",         cardType: "Hero" },
  { id: 302, playerName: "César Montes",       country: "Mexico",         cardType: "Hero" },
  { id: 303, playerName: "Héctor Moreno",      country: "Mexico",         cardType: "Hero" },
  { id: 304, playerName: "Jesús Gallardo",     country: "Mexico",         cardType: "Hero" },
  { id: 305, playerName: "Edson Álvarez",      country: "Mexico",         cardType: "Hero" },
  { id: 306, playerName: "Andrés Guardado",    country: "Mexico",         cardType: "Hero" },
  { id: 307, playerName: "Alexis Vega",        country: "Mexico",         cardType: "Hero" },
  { id: 308, playerName: "Roberto Alvarado",   country: "Mexico",         cardType: "Hero" },
  { id: 309, playerName: "Raúl Jiménez",       country: "Mexico",         cardType: "Hero" },

  // ── Morocco (310–321) ───────────────────────────────────────────────────
  { id: 310, playerName: "Achraf Hakimi",      country: "Morocco",        cardType: "Fan Favourite" },
  { id: 311, playerName: "Team Logo",          country: "Morocco",        cardType: "Team Logo" },
  { id: 312, playerName: "Youssef En-Nesyri",  country: "Morocco",        cardType: "Icon" },
  { id: 313, playerName: "Yassine Bounou",     country: "Morocco",        cardType: "Hero" },
  { id: 314, playerName: "Nayef Aguerd",       country: "Morocco",        cardType: "Hero" },
  { id: 315, playerName: "Romain Saïss",       country: "Morocco",        cardType: "Hero" },
  { id: 316, playerName: "Noussair Mazraoui",  country: "Morocco",        cardType: "Hero" },
  { id: 317, playerName: "Sofyan Amrabat",     country: "Morocco",        cardType: "Hero" },
  { id: 318, playerName: "Azzedine Ounahi",    country: "Morocco",        cardType: "Hero" },
  { id: 319, playerName: "Hakim Ziyech",       country: "Morocco",        cardType: "Hero" },
  { id: 320, playerName: "Soufiane Boufal",    country: "Morocco",        cardType: "Hero" },
  { id: 321, playerName: "Walid Cheddira",     country: "Morocco",        cardType: "Hero" },

  // ── Netherlands (322–333) ───────────────────────────────────────────────
  { id: 322, playerName: "Frenkie de Jong",    country: "Netherlands",    cardType: "Fan Favourite" },
  { id: 323, playerName: "Team Logo",          country: "Netherlands",    cardType: "Team Logo" },
  { id: 324, playerName: "Virgil van Dijk",    country: "Netherlands",    cardType: "Icon" },
  { id: 325, playerName: "Andries Noppert",    country: "Netherlands",    cardType: "Hero" },
  { id: 326, playerName: "Denzel Dumfries",    country: "Netherlands",    cardType: "Hero" },
  { id: 327, playerName: "Nathan Aké",         country: "Netherlands",    cardType: "Hero" },
  { id: 328, playerName: "Stefan de Vrij",     country: "Netherlands",    cardType: "Hero" },
  { id: 329, playerName: "Daley Blind",        country: "Netherlands",    cardType: "Hero" },
  { id: 330, playerName: "Xavi Simons",        country: "Netherlands",    cardType: "Hero" },
  { id: 331, playerName: "Tijjani Reijnders",  country: "Netherlands",    cardType: "Hero" },
  { id: 332, playerName: "Memphis Depay",      country: "Netherlands",    cardType: "Hero" },
  { id: 333, playerName: "Cody Gakpo",         country: "Netherlands",    cardType: "Hero" },

  // ── New Zealand (334–345) ───────────────────────────────────────────────
  { id: 334, playerName: "Chris Wood",         country: "New Zealand",    cardType: "Fan Favourite" },
  { id: 335, playerName: "Team Logo",          country: "New Zealand",    cardType: "Team Logo" },
  { id: 336, playerName: "Bill Tuilagi",       country: "New Zealand",    cardType: "Icon" },
  { id: 337, playerName: "Stefan Marinovic",   country: "New Zealand",    cardType: "Hero" },
  { id: 338, playerName: "Liberato Cacace",    country: "New Zealand",    cardType: "Hero" },
  { id: 339, playerName: "Winston Reid",       country: "New Zealand",    cardType: "Hero" },
  { id: 340, playerName: "Tommy Smith",        country: "New Zealand",    cardType: "Hero" },
  { id: 341, playerName: "Joe Bell",           country: "New Zealand",    cardType: "Hero" },
  { id: 342, playerName: "Clayton Lewis",      country: "New Zealand",    cardType: "Hero" },
  { id: 343, playerName: "Ryan Thomas",        country: "New Zealand",    cardType: "Hero" },
  { id: 344, playerName: "Elijah Just",        country: "New Zealand",    cardType: "Hero" },
  { id: 345, playerName: "Callan Elliot",      country: "New Zealand",    cardType: "Hero" },

  // ── Nigeria (346–357) ───────────────────────────────────────────────────
  { id: 346, playerName: "Victor Osimhen",     country: "Nigeria",        cardType: "Fan Favourite" },
  { id: 347, playerName: "Team Logo",          country: "Nigeria",        cardType: "Team Logo" },
  { id: 348, playerName: "Wilfred Ndidi",      country: "Nigeria",        cardType: "Icon" },
  { id: 349, playerName: "Francis Uzoho",      country: "Nigeria",        cardType: "Hero" },
  { id: 350, playerName: "Calvin Bassey",      country: "Nigeria",        cardType: "Hero" },
  { id: 351, playerName: "Leon Balogun",       country: "Nigeria",        cardType: "Hero" },
  { id: 352, playerName: "Zaidu Sanusi",       country: "Nigeria",        cardType: "Hero" },
  { id: 353, playerName: "Frank Onyeka",       country: "Nigeria",        cardType: "Hero" },
  { id: 354, playerName: "Joe Aribo",          country: "Nigeria",        cardType: "Hero" },
  { id: 355, playerName: "Alex Iwobi",         country: "Nigeria",        cardType: "Hero" },
  { id: 356, playerName: "Kelechi Iheanacho",  country: "Nigeria",        cardType: "Hero" },
  { id: 357, playerName: "Samuel Chukwueze",   country: "Nigeria",        cardType: "Hero" },

  // ── Panama (358–369) ────────────────────────────────────────────────────
  { id: 358, playerName: "Adalberto Carrasquilla", country: "Panama",     cardType: "Fan Favourite" },
  { id: 359, playerName: "Team Logo",          country: "Panama",         cardType: "Team Logo" },
  { id: 360, playerName: "Rolando Blackburn",  country: "Panama",         cardType: "Icon" },
  { id: 361, playerName: "Luis Mejía",         country: "Panama",         cardType: "Hero" },
  { id: 362, playerName: "Fidel Escobar",      country: "Panama",         cardType: "Hero" },
  { id: 363, playerName: "Roderick Miller",    country: "Panama",         cardType: "Hero" },
  { id: 364, playerName: "Éric Davis",         country: "Panama",         cardType: "Hero" },
  { id: 365, playerName: "César Yanis",        country: "Panama",         cardType: "Hero" },
  { id: 366, playerName: "Andrés Andrade",     country: "Panama",         cardType: "Hero" },
  { id: 367, playerName: "Édgar Barcenas",     country: "Panama",         cardType: "Hero" },
  { id: 368, playerName: "Julio Dely Valdés Jr.", country: "Panama",      cardType: "Hero" },
  { id: 369, playerName: "Ismael Díaz",        country: "Panama",         cardType: "Hero" },

  // ── Paraguay (370–381) ──────────────────────────────────────────────────
  { id: 370, playerName: "Miguel Almirón",     country: "Paraguay",       cardType: "Fan Favourite" },
  { id: 371, playerName: "Team Logo",          country: "Paraguay",       cardType: "Team Logo" },
  { id: 372, playerName: "Gustavo Gómez",      country: "Paraguay",       cardType: "Icon" },
  { id: 373, playerName: "Antony Silva",       country: "Paraguay",       cardType: "Hero" },
  { id: 374, playerName: "Robert Rojas",       country: "Paraguay",       cardType: "Hero" },
  { id: 375, playerName: "Junior Alonso",      country: "Paraguay",       cardType: "Hero" },
  { id: 376, playerName: "Júnior Ortiz",       country: "Paraguay",       cardType: "Hero" },
  { id: 377, playerName: "Matías Villasanti",  country: "Paraguay",       cardType: "Hero" },
  { id: 378, playerName: "Andrés Cubas",       country: "Paraguay",       cardType: "Hero" },
  { id: 379, playerName: "Jorge Morel",        country: "Paraguay",       cardType: "Hero" },
  { id: 380, playerName: "Antonio Sanabria",   country: "Paraguay",       cardType: "Hero" },
  { id: 381, playerName: "Ángel Romero",       country: "Paraguay",       cardType: "Hero" },

  // ── Peru (382–393) ──────────────────────────────────────────────────────
  { id: 382, playerName: "Christian Cueva",    country: "Peru",           cardType: "Fan Favourite" },
  { id: 383, playerName: "Team Logo",          country: "Peru",           cardType: "Team Logo" },
  { id: 384, playerName: "Paolo Guerrero",     country: "Peru",           cardType: "Icon" },
  { id: 385, playerName: "Pedro Gallese",      country: "Peru",           cardType: "Hero" },
  { id: 386, playerName: "Luis Advíncula",     country: "Peru",           cardType: "Hero" },
  { id: 387, playerName: "Carlos Zambrano",    country: "Peru",           cardType: "Hero" },
  { id: 388, playerName: "Alexander Callens",  country: "Peru",           cardType: "Hero" },
  { id: 389, playerName: "Yoshimar Yotún",     country: "Peru",           cardType: "Hero" },
  { id: 390, playerName: "Renato Tapia",       country: "Peru",           cardType: "Hero" },
  { id: 391, playerName: "André Carrillo",     country: "Peru",           cardType: "Hero" },
  { id: 392, playerName: "Edison Flores",      country: "Peru",           cardType: "Hero" },
  { id: 393, playerName: "Gianluca Lapadula",  country: "Peru",           cardType: "Hero" },

  // ── Portugal (394–405) ──────────────────────────────────────────────────
  { id: 394, playerName: "Bernardo Silva",     country: "Portugal",       cardType: "Fan Favourite" },
  { id: 395, playerName: "Team Logo",          country: "Portugal",       cardType: "Team Logo" },
  { id: 396, playerName: "Cristiano Ronaldo",  country: "Portugal",       cardType: "Icon" },
  { id: 397, playerName: "Rui Patrício",       country: "Portugal",       cardType: "Hero" },
  { id: 398, playerName: "João Cancelo",       country: "Portugal",       cardType: "Hero" },
  { id: 399, playerName: "Rúben Dias",         country: "Portugal",       cardType: "Hero" },
  { id: 400, playerName: "Pepe",               country: "Portugal",       cardType: "Hero" },
  { id: 401, playerName: "Vitinha",            country: "Portugal",       cardType: "Hero" },
  { id: 402, playerName: "Bruno Fernandes",    country: "Portugal",       cardType: "Hero" },
  { id: 403, playerName: "João Félix",         country: "Portugal",       cardType: "Hero" },
  { id: 404, playerName: "Rafael Leão",        country: "Portugal",       cardType: "Hero" },
  { id: 405, playerName: "Gonçalo Ramos",      country: "Portugal",       cardType: "Hero" },

  // ── Qatar (406–417) ─────────────────────────────────────────────────────
  { id: 406, playerName: "Akram Afif",         country: "Qatar",          cardType: "Fan Favourite" },
  { id: 407, playerName: "Team Logo",          country: "Qatar",          cardType: "Team Logo" },
  { id: 408, playerName: "Hassan Al-Haydos",   country: "Qatar",          cardType: "Icon" },
  { id: 409, playerName: "Meshaal Barsham",    country: "Qatar",          cardType: "Hero" },
  { id: 410, playerName: "Pedro Miguel",       country: "Qatar",          cardType: "Hero" },
  { id: 411, playerName: "Bassam Al-Rawi",     country: "Qatar",          cardType: "Hero" },
  { id: 412, playerName: "Tarek Salman",       country: "Qatar",          cardType: "Hero" },
  { id: 413, playerName: "Karim Boudiaf",      country: "Qatar",          cardType: "Hero" },
  { id: 414, playerName: "Abdulaziz Hatem",    country: "Qatar",          cardType: "Hero" },
  { id: 415, playerName: "Ismail Mohamad",     country: "Qatar",          cardType: "Hero" },
  { id: 416, playerName: "Almoez Ali",         country: "Qatar",          cardType: "Hero" },
  { id: 417, playerName: "Mohammed Muntari",   country: "Qatar",          cardType: "Hero" },

  // ── Saudi Arabia (418–429) ──────────────────────────────────────────────
  { id: 418, playerName: "Salem Al-Dawsari",   country: "Saudi Arabia",   cardType: "Fan Favourite" },
  { id: 419, playerName: "Team Logo",          country: "Saudi Arabia",   cardType: "Team Logo" },
  { id: 420, playerName: "Mohammed Al-Owais",  country: "Saudi Arabia",   cardType: "Icon" },
  { id: 421, playerName: "Yasser Al-Shahrani", country: "Saudi Arabia",   cardType: "Hero" },
  { id: 422, playerName: "Ali Al-Bulaihi",     country: "Saudi Arabia",   cardType: "Hero" },
  { id: 423, playerName: "Abdulelah Al-Malki", country: "Saudi Arabia",   cardType: "Hero" },
  { id: 424, playerName: "Mohamed Kanno",      country: "Saudi Arabia",   cardType: "Hero" },
  { id: 425, playerName: "Riyadh Sharahili",   country: "Saudi Arabia",   cardType: "Hero" },
  { id: 426, playerName: "Hattan Bahebri",     country: "Saudi Arabia",   cardType: "Hero" },
  { id: 427, playerName: "Firas Al-Buraikan",  country: "Saudi Arabia",   cardType: "Hero" },
  { id: 428, playerName: "Sami Al-Najei",      country: "Saudi Arabia",   cardType: "Hero" },
  { id: 429, playerName: "Yasir Al-Shahrani",  country: "Saudi Arabia",   cardType: "Hero" },

  // ── Senegal (430–441) ───────────────────────────────────────────────────
  { id: 430, playerName: "Ismaïla Sarr",       country: "Senegal",        cardType: "Fan Favourite" },
  { id: 431, playerName: "Team Logo",          country: "Senegal",        cardType: "Team Logo" },
  { id: 432, playerName: "Sadio Mané",         country: "Senegal",        cardType: "Icon" },
  { id: 433, playerName: "Édouard Mendy",      country: "Senegal",        cardType: "Hero" },
  { id: 434, playerName: "Kalidou Koulibaly",  country: "Senegal",        cardType: "Hero" },
  { id: 435, playerName: "Abdou Diallo",       country: "Senegal",        cardType: "Hero" },
  { id: 436, playerName: "Youssouf Sabaly",    country: "Senegal",        cardType: "Hero" },
  { id: 437, playerName: "Nampalys Mendy",     country: "Senegal",        cardType: "Hero" },
  { id: 438, playerName: "Idrissa Gueye",      country: "Senegal",        cardType: "Hero" },
  { id: 439, playerName: "Pape Matar Sarr",    country: "Senegal",        cardType: "Hero" },
  { id: 440, playerName: "Boulaye Dia",        country: "Senegal",        cardType: "Hero" },
  { id: 441, playerName: "Nicolas Jackson",    country: "Senegal",        cardType: "Hero" },

  // ── Serbia (442–453) ────────────────────────────────────────────────────
  { id: 442, playerName: "Aleksandar Mitrović", country: "Serbia",        cardType: "Fan Favourite" },
  { id: 443, playerName: "Team Logo",           country: "Serbia",        cardType: "Team Logo" },
  { id: 444, playerName: "Dušan Vlahović",      country: "Serbia",        cardType: "Icon" },
  { id: 445, playerName: "Predrag Rajković",    country: "Serbia",        cardType: "Hero" },
  { id: 446, playerName: "Strahinja Pavlović",  country: "Serbia",        cardType: "Hero" },
  { id: 447, playerName: "Nikola Milenković",   country: "Serbia",        cardType: "Hero" },
  { id: 448, playerName: "Miloš Veljković",     country: "Serbia",        cardType: "Hero" },
  { id: 449, playerName: "Nemanja Gudelj",      country: "Serbia",        cardType: "Hero" },
  { id: 450, playerName: "Sasa Lukic",          country: "Serbia",        cardType: "Hero" },
  { id: 451, playerName: "Filip Kostić",        country: "Serbia",        cardType: "Hero" },
  { id: 452, playerName: "Dušan Tadić",         country: "Serbia",        cardType: "Hero" },
  { id: 453, playerName: "Luka Jović",          country: "Serbia",        cardType: "Hero" },

  // ── Slovenia (454–465) ──────────────────────────────────────────────────
  { id: 454, playerName: "Jan Oblak",           country: "Slovenia",      cardType: "Fan Favourite" },
  { id: 455, playerName: "Team Logo",           country: "Slovenia",      cardType: "Team Logo" },
  { id: 456, playerName: "Benjamin Šeško",      country: "Slovenia",      cardType: "Icon" },
  { id: 457, playerName: "Vid Belec",           country: "Slovenia",      cardType: "Hero" },
  { id: 458, playerName: "Jure Balkovec",       country: "Slovenia",      cardType: "Hero" },
  { id: 459, playerName: "Miha Blažič",         country: "Slovenia",      cardType: "Hero" },
  { id: 460, playerName: "Jaka Bijol",          country: "Slovenia",      cardType: "Hero" },
  { id: 461, playerName: "Jon Gorenc-Stanković", country: "Slovenia",     cardType: "Hero" },
  { id: 462, playerName: "Adam Gnezda Čerin",   country: "Slovenia",      cardType: "Hero" },
  { id: 463, playerName: "Josip Iličić",        country: "Slovenia",      cardType: "Hero" },
  { id: 464, playerName: "Andraž Šporar",       country: "Slovenia",      cardType: "Hero" },
  { id: 465, playerName: "Žan Celar",           country: "Slovenia",      cardType: "Hero" },

  // ── South Africa (466–477) ──────────────────────────────────────────────
  { id: 466, playerName: "Percy Tau",           country: "South Africa",  cardType: "Fan Favourite" },
  { id: 467, playerName: "Team Logo",           country: "South Africa",  cardType: "Team Logo" },
  { id: 468, playerName: "Themba Zwane",        country: "South Africa",  cardType: "Icon" },
  { id: 469, playerName: "Ronwen Williams",     country: "South Africa",  cardType: "Hero" },
  { id: 470, playerName: "Reeve Frosler",       country: "South Africa",  cardType: "Hero" },
  { id: 471, playerName: "Sifiso Hlanti",       country: "South Africa",  cardType: "Hero" },
  { id: 472, playerName: "Mothobi Mvala",       country: "South Africa",  cardType: "Hero" },
  { id: 473, playerName: "Bryce Moon",          country: "South Africa",  cardType: "Hero" },
  { id: 474, playerName: "Teboho Mokoena",      country: "South Africa",  cardType: "Hero" },
  { id: 475, playerName: "Themba Zwane",        country: "South Africa",  cardType: "Hero" },
  { id: 476, playerName: "Lyle Foster",         country: "South Africa",  cardType: "Hero" },
  { id: 477, playerName: "Evidence Makgopa",    country: "South Africa",  cardType: "Hero" },

  // ── Spain (478–489) ─────────────────────────────────────────────────────
  { id: 478, playerName: "Pedri",               country: "Spain",         cardType: "Fan Favourite" },
  { id: 479, playerName: "Team Logo",           country: "Spain",         cardType: "Team Logo" },
  { id: 480, playerName: "Lamine Yamal",        country: "Spain",         cardType: "Icon" },
  { id: 481, playerName: "Unai Simón",          country: "Spain",         cardType: "Hero" },
  { id: 482, playerName: "Dani Carvajal",       country: "Spain",         cardType: "Hero" },
  { id: 483, playerName: "Aymeric Laporte",     country: "Spain",         cardType: "Hero" },
  { id: 484, playerName: "Pau Cubarsí",         country: "Spain",         cardType: "Hero" },
  { id: 485, playerName: "Alejandro Grimaldo",  country: "Spain",         cardType: "Hero" },
  { id: 486, playerName: "Rodri",               country: "Spain",         cardType: "Hero" },
  { id: 487, playerName: "Fabian Ruiz",         country: "Spain",         cardType: "Hero" },
  { id: 488, playerName: "Nico Williams",       country: "Spain",         cardType: "Hero" },
  { id: 489, playerName: "Álvaro Morata",       country: "Spain",         cardType: "Hero" },

  // ── Switzerland (490–501) ───────────────────────────────────────────────
  { id: 490, playerName: "Granit Xhaka",        country: "Switzerland",   cardType: "Fan Favourite" },
  { id: 491, playerName: "Team Logo",           country: "Switzerland",   cardType: "Team Logo" },
  { id: 492, playerName: "Xherdan Shaqiri",     country: "Switzerland",   cardType: "Icon" },
  { id: 493, playerName: "Yann Sommer",         country: "Switzerland",   cardType: "Hero" },
  { id: 494, playerName: "Silvan Widmer",       country: "Switzerland",   cardType: "Hero" },
  { id: 495, playerName: "Manuel Akanji",       country: "Switzerland",   cardType: "Hero" },
  { id: 496, playerName: "Nico Elvedi",         country: "Switzerland",   cardType: "Hero" },
  { id: 497, playerName: "Denis Zakaria",       country: "Switzerland",   cardType: "Hero" },
  { id: 498, playerName: "Remo Freuler",        country: "Switzerland",   cardType: "Hero" },
  { id: 499, playerName: "Ruben Vargas",        country: "Switzerland",   cardType: "Hero" },
  { id: 500, playerName: "Noah Okafor",         country: "Switzerland",   cardType: "Hero" },
  { id: 501, playerName: "Breel Embolo",        country: "Switzerland",   cardType: "Hero" },

  // ── United States (502–513) ─────────────────────────────────────────────
  { id: 502, playerName: "Christian Pulisic",   country: "United States", cardType: "Fan Favourite" },
  { id: 503, playerName: "Team Logo",           country: "United States", cardType: "Team Logo" },
  { id: 504, playerName: "Tyler Adams",         country: "United States", cardType: "Icon" },
  { id: 505, playerName: "Matt Turner",         country: "United States", cardType: "Hero" },
  { id: 506, playerName: "DeAndre Yedlin",      country: "United States", cardType: "Hero" },
  { id: 507, playerName: "Walker Zimmerman",    country: "United States", cardType: "Hero" },
  { id: 508, playerName: "Miles Robinson",      country: "United States", cardType: "Hero" },
  { id: 509, playerName: "Weston McKennie",     country: "United States", cardType: "Hero" },
  { id: 510, playerName: "Yunus Musah",         country: "United States", cardType: "Hero" },
  { id: 511, playerName: "Gio Reyna",           country: "United States", cardType: "Hero" },
  { id: 512, playerName: "Tim Weah",            country: "United States", cardType: "Hero" },
  { id: 513, playerName: "Folarin Balogun",     country: "United States", cardType: "Hero" },

  // ── Uruguay (514–525) ───────────────────────────────────────────────────
  { id: 514, playerName: "Darwin Núñez",        country: "Uruguay",       cardType: "Fan Favourite" },
  { id: 515, playerName: "Team Logo",           country: "Uruguay",       cardType: "Team Logo" },
  { id: 516, playerName: "Federico Valverde",   country: "Uruguay",       cardType: "Icon" },
  { id: 517, playerName: "Sergio Rochet",       country: "Uruguay",       cardType: "Hero" },
  { id: 518, playerName: "Matías Viña",         country: "Uruguay",       cardType: "Hero" },
  { id: 519, playerName: "José María Giménez",  country: "Uruguay",       cardType: "Hero" },
  { id: 520, playerName: "Diego Godín",         country: "Uruguay",       cardType: "Hero" },
  { id: 521, playerName: "Matías Vecino",       country: "Uruguay",       cardType: "Hero" },
  { id: 522, playerName: "Rodrigo Bentancur",   country: "Uruguay",       cardType: "Hero" },
  { id: 523, playerName: "Facundo Pellistri",   country: "Uruguay",       cardType: "Hero" },
  { id: 524, playerName: "Giorgian de Arrascaeta", country: "Uruguay",    cardType: "Hero" },
  { id: 525, playerName: "Luis Suárez",         country: "Uruguay",       cardType: "Hero" },

  // ── Venezuela (526–537) ─────────────────────────────────────────────────
  { id: 526, playerName: "Salomón Rondón",      country: "Venezuela",     cardType: "Fan Favourite" },
  { id: 527, playerName: "Team Logo",           country: "Venezuela",     cardType: "Team Logo" },
  { id: 528, playerName: "Yangel Herrera",      country: "Venezuela",     cardType: "Icon" },
  { id: 529, playerName: "Wuilker Faríñez",     country: "Venezuela",     cardType: "Hero" },
  { id: 530, playerName: "Alexander González",  country: "Venezuela",     cardType: "Hero" },
  { id: 531, playerName: "Mikel Villanueva",    country: "Venezuela",     cardType: "Hero" },
  { id: 532, playerName: "Nahuel Ferraresi",    country: "Venezuela",     cardType: "Hero" },
  { id: 533, playerName: "Tomás Rincón",        country: "Venezuela",     cardType: "Hero" },
  { id: 534, playerName: "Jefferson Savarino",  country: "Venezuela",     cardType: "Hero" },
  { id: 535, playerName: "Rómulo Otero",        country: "Venezuela",     cardType: "Hero" },
  { id: 536, playerName: "Darwin Machís",       country: "Venezuela",     cardType: "Hero" },
  { id: 537, playerName: "Josef Martínez",      country: "Venezuela",     cardType: "Hero" },

  // ── Master Rookies (538–553) ─────────────────────────────────────────────
  { id: 538, playerName: "Pedri",               country: "Spain",         cardType: "Master Rookie" },
  { id: 539, playerName: "Gavi",                country: "Spain",         cardType: "Master Rookie" },
  { id: 540, playerName: "Lamine Yamal",        country: "Spain",         cardType: "Master Rookie" },
  { id: 541, playerName: "Jude Bellingham",     country: "England",       cardType: "Master Rookie" },
  { id: 542, playerName: "Cole Palmer",         country: "England",       cardType: "Master Rookie" },
  { id: 543, playerName: "Eduardo Camavinga",   country: "France",        cardType: "Master Rookie" },
  { id: 544, playerName: "Warren Zaïre-Emery",  country: "France",        cardType: "Master Rookie" },
  { id: 545, playerName: "Florian Wirtz",       country: "Germany",       cardType: "Master Rookie" },
  { id: 546, playerName: "Jamal Musiala",       country: "Germany",       cardType: "Master Rookie" },
  { id: 547, playerName: "Giuliano Simeone",    country: "Argentina",     cardType: "Master Rookie" },
  { id: 548, playerName: "Matheus Cunha",       country: "Brazil",        cardType: "Master Rookie" },
  { id: 549, playerName: "Joško Gvardiol",      country: "Croatia",       cardType: "Master Rookie" },
  { id: 550, playerName: "Tijjani Reijnders",   country: "Netherlands",   cardType: "Master Rookie" },
  { id: 551, playerName: "Xavi Simons",         country: "Netherlands",   cardType: "Master Rookie" },
  { id: 552, playerName: "Mohammed Kudus",      country: "Ghana",         cardType: "Master Rookie" },
  { id: 553, playerName: "Piero Hincapié",      country: "Ecuador",       cardType: "Master Rookie" },

  // ── Top Keepers (554–562) ────────────────────────────────────────────────
  { id: 554, playerName: "Manuel Neuer",        country: "Germany",       cardType: "Top Keeper" },
  { id: 555, playerName: "Thibaut Courtois",    country: "Belgium",       cardType: "Top Keeper" },
  { id: 556, playerName: "Jan Oblak",           country: "Slovenia",      cardType: "Top Keeper" },
  { id: 557, playerName: "Alisson",             country: "Brazil",        cardType: "Top Keeper" },
  { id: 558, playerName: "Emiliano Martínez",   country: "Argentina",     cardType: "Top Keeper" },
  { id: 559, playerName: "Jordan Pickford",     country: "England",       cardType: "Top Keeper" },
  { id: 560, playerName: "Yann Sommer",         country: "Switzerland",   cardType: "Top Keeper" },
  { id: 561, playerName: "Keylor Navas",        country: "Costa Rica",    cardType: "Top Keeper" },
  { id: 562, playerName: "Mathew Ryan",         country: "Australia",     cardType: "Top Keeper" },

  // ── Defensive Rocks (563–571) ────────────────────────────────────────────
  { id: 563, playerName: "Virgil van Dijk",     country: "Netherlands",   cardType: "Defensive Rock" },
  { id: 564, playerName: "Rúben Dias",          country: "Portugal",      cardType: "Defensive Rock" },
  { id: 565, playerName: "Kim Min-Jae",         country: "Korea Republic", cardType: "Defensive Rock" },
  { id: 566, playerName: "Kalidou Koulibaly",   country: "Senegal",       cardType: "Defensive Rock" },
  { id: 567, playerName: "Cristian Romero",     country: "Argentina",     cardType: "Defensive Rock" },
  { id: 568, playerName: "Antonio Rüdiger",     country: "Germany",       cardType: "Defensive Rock" },
  { id: 569, playerName: "Joško Gvardiol",      country: "Croatia",       cardType: "Defensive Rock" },
  { id: 570, playerName: "Dávinson Sánchez",    country: "Colombia",      cardType: "Defensive Rock" },
  { id: 571, playerName: "Achraf Hakimi",       country: "Morocco",       cardType: "Defensive Rock" },

  // ── Midfield Maestros (572–589) ──────────────────────────────────────────
  { id: 572, playerName: "Luka Modrić",         country: "Croatia",       cardType: "Midfield Maestro" },
  { id: 573, playerName: "N'Golo Kanté",        country: "France",        cardType: "Midfield Maestro" },
  { id: 574, playerName: "Toni Kroos",          country: "Germany",       cardType: "Midfield Maestro" },
  { id: 575, playerName: "Rodri",               country: "Spain",         cardType: "Midfield Maestro" },
  { id: 576, playerName: "Pedri",               country: "Spain",         cardType: "Midfield Maestro" },
  { id: 577, playerName: "Declan Rice",         country: "England",       cardType: "Midfield Maestro" },
  { id: 578, playerName: "Jude Bellingham",     country: "England",       cardType: "Midfield Maestro" },
  { id: 579, playerName: "Kevin de Bruyne",     country: "Belgium",       cardType: "Midfield Maestro" },
  { id: 580, playerName: "Bruno Fernandes",     country: "Portugal",      cardType: "Midfield Maestro" },
  { id: 581, playerName: "Casemiro",            country: "Brazil",        cardType: "Midfield Maestro" },
  { id: 582, playerName: "Frenkie de Jong",     country: "Netherlands",   cardType: "Midfield Maestro" },
  { id: 583, playerName: "Granit Xhaka",        country: "Switzerland",   cardType: "Midfield Maestro" },
  { id: 584, playerName: "Moisés Caicedo",      country: "Ecuador",       cardType: "Midfield Maestro" },
  { id: 585, playerName: "Sofyan Amrabat",      country: "Morocco",       cardType: "Midfield Maestro" },
  { id: 586, playerName: "Thomas Partey",       country: "Ghana",         cardType: "Midfield Maestro" },
  { id: 587, playerName: "Wilfred Ndidi",       country: "Nigeria",       cardType: "Midfield Maestro" },
  { id: 588, playerName: "Yves Bissouma",       country: "Mali",          cardType: "Midfield Maestro" },
  { id: 589, playerName: "Mateo Kovačić",       country: "Croatia",       cardType: "Midfield Maestro" },

  // ── Goal Machines (590–611) ──────────────────────────────────────────────
  { id: 590, playerName: "Kylian Mbappé",       country: "France",        cardType: "Goal Machine" },
  { id: 591, playerName: "Harry Kane",          country: "England",       cardType: "Goal Machine" },
  { id: 592, playerName: "Erling Haaland",      country: "Norway",        cardType: "Goal Machine" },
  { id: 593, playerName: "Cristiano Ronaldo",   country: "Portugal",      cardType: "Goal Machine" },
  { id: 594, playerName: "Lionel Messi",        country: "Argentina",     cardType: "Goal Machine" },
  { id: 595, playerName: "Vinícius Júnior",     country: "Brazil",        cardType: "Goal Machine" },
  { id: 596, playerName: "Mohamed Salah",       country: "Egypt",         cardType: "Goal Machine" },
  { id: 597, playerName: "Lamine Yamal",        country: "Spain",         cardType: "Goal Machine" },
  { id: 598, playerName: "Son Heung-Min",       country: "Korea Republic", cardType: "Goal Machine" },
  { id: 599, playerName: "Julián Álvarez",      country: "Argentina",     cardType: "Goal Machine" },
  { id: 600, playerName: "Victor Osimhen",      country: "Nigeria",       cardType: "Goal Machine" },
  { id: 601, playerName: "Dušan Vlahović",      country: "Serbia",        cardType: "Goal Machine" },
  { id: 602, playerName: "Jonathan David",      country: "Canada",        cardType: "Goal Machine" },
  { id: 603, playerName: "Raphinha",            country: "Brazil",        cardType: "Goal Machine" },
  { id: 604, playerName: "Bukayo Saka",         country: "England",       cardType: "Goal Machine" },
  { id: 605, playerName: "Antoine Griezmann",   country: "France",        cardType: "Goal Machine" },
  { id: 606, playerName: "Darwin Núñez",        country: "Uruguay",       cardType: "Goal Machine" },
  { id: 607, playerName: "Mehdi Taremi",        country: "Iran",          cardType: "Goal Machine" },
  { id: 608, playerName: "Luis Díaz",           country: "Colombia",      cardType: "Goal Machine" },
  { id: 609, playerName: "Benjamin Šeško",      country: "Slovenia",      cardType: "Goal Machine" },
  { id: 610, playerName: "Cody Gakpo",          country: "Netherlands",   cardType: "Goal Machine" },
  { id: 611, playerName: "Christian Pulisic",   country: "United States", cardType: "Goal Machine" },

  // ── Contenders (612–614) ─────────────────────────────────────────────────
  { id: 612, playerName: "Argentina",           country: "Argentina",     cardType: "Contender" },
  { id: 613, playerName: "Brazil",              country: "Brazil",        cardType: "Contender" },
  { id: 614, playerName: "France",              country: "France",        cardType: "Contender" },

  // ── Official Mascots (615–617) ───────────────────────────────────────────
  { id: 615, playerName: "Striker — USA Mascot",   country: "United States", cardType: "Mascot" },
  { id: 616, playerName: "Cachito — Mexico Mascot", country: "Mexico",       cardType: "Mascot" },
  { id: 617, playerName: "Max — Canada Mascot",     country: "Canada",       cardType: "Mascot" },

  // ── Official Emblem (618) ────────────────────────────────────────────────
  { id: 618, playerName: "Official Emblem WC 2026", country: "Qatar",        cardType: "Contender" },
];

// O(1) lookup map by card id
export const CARDS_BY_ID = Object.fromEntries(CARDS.map(c => [c.id, c]));

// All unique team names sorted alphabetically
export const TEAMS = [...new Set(CARDS.map(c => c.country))].sort();

// Card type enum in canonical display order
export const CARD_TYPES = [
  "Hero",
  "Icon",
  "Fan Favourite",
  "Team Logo",
  "Golden Baller",
  "Contender",
  "Master Rookie",
  "Top Keeper",
  "Defensive Rock",
  "Midfield Maestro",
  "Goal Machine",
  "Mascot",
];
