// js/cards-data.js
// Complete card checklist — Panini Adrenalyn XL FIFA World Cup 2026 (630 cards)

export const CARDS = [

  // ── Golden Ballers (1–9) ────────────────────────────────────────────────
  { id: 1,  playerName: "Lionel Messi", country: "Argentina", cardType: "Golden Baller" },
  { id: 2,  playerName: "Vinícius Júnior", country: "Brazil", cardType: "Golden Baller" },
  { id: 3,  playerName: "Mohamed Salah", country: "Egypt", cardType: "Golden Baller" },
  { id: 4,  playerName: "Harry Kane", country: "England", cardType: "Golden Baller" },
  { id: 5,  playerName: "Kylian Mbappé", country: "France", cardType: "Golden Baller" },
  { id: 6,  playerName: "Son Heung-Min", country: "Korea Republic", cardType: "Golden Baller" },
  { id: 7,  playerName: "Erling Haaland", country: "Norway", cardType: "Golden Baller" },
  { id: 8,  playerName: "Cristiano Ronaldo", country: "Portugal", cardType: "Golden Baller" },
  { id: 9,  playerName: "Lamine Yamal", country: "Spain", cardType: "Golden Baller" },

  // ── Algeria (10–21) ───────────────────────────────────────
  { id: 10,    playerName: "Rayan Aït-Nouri",  country: "Algeria", cardType: "Fan Favourite" },
  { id: 11,  playerName: "Team Logo", country: "Algeria", cardType: "Team Logo" },
  { id: 12,  playerName: "Riyad Mahrez", country: "Algeria", cardType: "Icon" },
  { id: 13, playerName: "Alexis Guendouz", country: "Algeria", cardType: "Hero" },
  { id: 14, playerName: "Ramy Bensebaini", country: "Algeria", cardType: "Hero" },
  { id: 15, playerName: "Youcef Atal", country: "Algeria", cardType: "Hero" },
  { id: 16, playerName: "Aïssa Mandi", country: "Algeria", cardType: "Hero" },
  { id: 17, playerName: "Nabil Bentaleb", country: "Algeria", cardType: "Hero" },
  { id: 18, playerName: "Saïd Benrahma", country: "Algeria", cardType: "Hero" },
  { id: 19, playerName: "Amine Gouiri", country: "Algeria", cardType: "Hero" },
  { id: 20, playerName: "Mohammed Amoura", country: "Algeria", cardType: "Hero" },
  { id: 21, playerName: "Baghdad Bounedjah", country: "Algeria", cardType: "Hero" },

  // ── Argentina (22–33) ─────────────────────────────────────
  { id: 22,    playerName: "Julián Álvarez",  country: "Argentina", cardType: "Fan Favourite" },
  { id: 23,  playerName: "Team Logo", country: "Argentina", cardType: "Team Logo" },
  { id: 24,  playerName: "Lionel Messi", country: "Argentina", cardType: "Icon" },
  { id: 25, playerName: "Emiliano Martínez", country: "Argentina", cardType: "Hero" },
  { id: 26, playerName: "Nahuel Molina", country: "Argentina", cardType: "Hero" },
  { id: 27, playerName: "Cristian Romero", country: "Argentina", cardType: "Hero" },
  { id: 28, playerName: "Nicolás Otamendi", country: "Argentina", cardType: "Hero" },
  { id: 29, playerName: "Enzo Fernández", country: "Argentina", cardType: "Hero" },
  { id: 30, playerName: "Alexis Mac Allister", country: "Argentina", cardType: "Hero" },
  { id: 31, playerName: "Rodrigo de Paul", country: "Argentina", cardType: "Hero" },
  { id: 32, playerName: "Giuliano Simeone", country: "Argentina", cardType: "Hero" },
  { id: 33, playerName: "Lautaro Martínez", country: "Argentina", cardType: "Hero" },

  // ── Australia (34–45) ─────────────────────────────────────
  { id: 34,    playerName: "Harry Souttar",  country: "Australia", cardType: "Fan Favourite" },
  { id: 35,  playerName: "Team Logo", country: "Australia", cardType: "Team Logo" },
  { id: 36,  playerName: "Mathew Ryan", country: "Australia", cardType: "Icon" },
  { id: 37, playerName: "Alessandro Circati", country: "Australia", cardType: "Hero" },
  { id: 38, playerName: "Jordan Bos", country: "Australia", cardType: "Hero" },
  { id: 39, playerName: "Lewis Miller", country: "Australia", cardType: "Hero" },
  { id: 40, playerName: "Miloš Degenek", country: "Australia", cardType: "Hero" },
  { id: 41, playerName: "Jackson Irvine", country: "Australia", cardType: "Hero" },
  { id: 42, playerName: "Riley McGree", country: "Australia", cardType: "Hero" },
  { id: 43, playerName: "Aiden O'Neill", country: "Australia", cardType: "Hero" },
  { id: 44, playerName: "Connor Metcalfe", country: "Australia", cardType: "Hero" },
  { id: 45, playerName: "Craig Goodwin", country: "Australia", cardType: "Hero" },

  // ── Austria (46–57) ───────────────────────────────────────
  { id: 46,    playerName: "Marko Arnautović",  country: "Austria", cardType: "Fan Favourite" },
  { id: 47,  playerName: "Team Logo", country: "Austria", cardType: "Team Logo" },
  { id: 48,  playerName: "David Alaba", country: "Austria", cardType: "Icon" },
  { id: 49, playerName: "Alexander Schlager", country: "Austria", cardType: "Hero" },
  { id: 50, playerName: "Kevin Danso", country: "Austria", cardType: "Hero" },
  { id: 51, playerName: "Philipp Lienhart", country: "Austria", cardType: "Hero" },
  { id: 52, playerName: "Konrad Laimer", country: "Austria", cardType: "Hero" },
  { id: 53, playerName: "Nicolas Seiwald", country: "Austria", cardType: "Hero" },
  { id: 54, playerName: "Marcel Sabitzer", country: "Austria", cardType: "Hero" },
  { id: 55, playerName: "Florian Grillitsch", country: "Austria", cardType: "Hero" },
  { id: 56, playerName: "Christoph Baumgartner", country: "Austria", cardType: "Hero" },
  { id: 57, playerName: "Michael Gregoritsch", country: "Austria", cardType: "Hero" },

  // ── Belgium (58–69) ───────────────────────────────────────
  { id: 58,    playerName: "Youri Tielemans",  country: "Belgium", cardType: "Fan Favourite" },
  { id: 59,  playerName: "Team Logo", country: "Belgium", cardType: "Team Logo" },
  { id: 60,  playerName: "Kevin De Bruyne", country: "Belgium", cardType: "Icon" },
  { id: 61, playerName: "Thibaut Courtois", country: "Belgium", cardType: "Hero" },
  { id: 62, playerName: "Arthur Theate", country: "Belgium", cardType: "Hero" },
  { id: 63, playerName: "Timothy Castagne", country: "Belgium", cardType: "Hero" },
  { id: 64, playerName: "Maxim De Cuyper", country: "Belgium", cardType: "Hero" },
  { id: 65, playerName: "Amadou Onana", country: "Belgium", cardType: "Hero" },
  { id: 66, playerName: "Jérémy Doku", country: "Belgium", cardType: "Hero" },
  { id: 67, playerName: "Charles De Ketelaere", country: "Belgium", cardType: "Hero" },
  { id: 68, playerName: "Leandro Trossard", country: "Belgium", cardType: "Hero" },
  { id: 69, playerName: "Romelu Lukaku", country: "Belgium", cardType: "Hero" },

  // ── Brazil (70–81) ────────────────────────────────────────
  { id: 70,    playerName: "Vinícius Júnior",  country: "Brazil", cardType: "Fan Favourite" },
  { id: 71,  playerName: "Team Logo", country: "Brazil", cardType: "Team Logo" },
  { id: 72,  playerName: "Marquinhos", country: "Brazil", cardType: "Icon" },
  { id: 73, playerName: "Alisson", country: "Brazil", cardType: "Hero" },
  { id: 74, playerName: "Danilo", country: "Brazil", cardType: "Hero" },
  { id: 75, playerName: "Éder Militão", country: "Brazil", cardType: "Hero" },
  { id: 76, playerName: "Gabriel Magalhães", country: "Brazil", cardType: "Hero" },
  { id: 77, playerName: "Casemiro", country: "Brazil", cardType: "Hero" },
  { id: 78, playerName: "Bruno Guimarães", country: "Brazil", cardType: "Hero" },
  { id: 79, playerName: "Rodrygo", country: "Brazil", cardType: "Hero" },
  { id: 80, playerName: "Matheus Cunha", country: "Brazil", cardType: "Hero" },
  { id: 81, playerName: "Raphinha", country: "Brazil", cardType: "Hero" },

  // ── Canada (82–93) ────────────────────────────────────────
  { id: 82,    playerName: "Jonathan David",  country: "Canada", cardType: "Fan Favourite" },
  { id: 83,  playerName: "Team Logo", country: "Canada", cardType: "Team Logo" },
  { id: 84,  playerName: "Alphonso Davies", country: "Canada", cardType: "Icon" },
  { id: 85, playerName: "Dayne St. Clair", country: "Canada", cardType: "Hero" },
  { id: 86, playerName: "Richie Laryea", country: "Canada", cardType: "Hero" },
  { id: 87, playerName: "Derek Cornelius", country: "Canada", cardType: "Hero" },
  { id: 88, playerName: "Stephen Eustaquio", country: "Canada", cardType: "Hero" },
  { id: 89, playerName: "Ismaël Koné", country: "Canada", cardType: "Hero" },
  { id: 90, playerName: "Jonathan Osorio", country: "Canada", cardType: "Hero" },
  { id: 91, playerName: "Jacob Shaffelburg", country: "Canada", cardType: "Hero" },
  { id: 92, playerName: "Tajon Buchanan", country: "Canada", cardType: "Hero" },
  { id: 93, playerName: "Cyle Larin", country: "Canada", cardType: "Hero" },

  // ── Cape Verde (94–105) ───────────────────────────────────
  { id: 94,    playerName: "Vozinha",  country: "Cape Verde", cardType: "Fan Favourite" },
  { id: 95,  playerName: "Team Logo", country: "Cape Verde", cardType: "Team Logo" },
  { id: 96,  playerName: "Ryan Mendes", country: "Cape Verde", cardType: "Icon" },
  { id: 97, playerName: "Logan Costa", country: "Cape Verde", cardType: "Hero" },
  { id: 98, playerName: "Pico", country: "Cape Verde", cardType: "Hero" },
  { id: 99, playerName: "Steven Moreira", country: "Cape Verde", cardType: "Hero" },
  { id: 100, playerName: "João Paulo", country: "Cape Verde", cardType: "Hero" },
  { id: 101, playerName: "Willy Semedo", country: "Cape Verde", cardType: "Hero" },
  { id: 102, playerName: "Jamiro Monteiro", country: "Cape Verde", cardType: "Hero" },
  { id: 103, playerName: "Kenny Rocha", country: "Cape Verde", cardType: "Hero" },
  { id: 104, playerName: "Garry Rodrigues", country: "Cape Verde", cardType: "Hero" },
  { id: 105, playerName: "Djaniny", country: "Cape Verde", cardType: "Hero" },

  // ── Colombia (106–117) ────────────────────────────────────
  { id: 106,    playerName: "James Rodríguez",  country: "Colombia", cardType: "Fan Favourite" },
  { id: 107,  playerName: "Team Logo", country: "Colombia", cardType: "Team Logo" },
  { id: 108,  playerName: "Luis Díaz", country: "Colombia", cardType: "Icon" },
  { id: 109, playerName: "Camilo Vargas", country: "Colombia", cardType: "Hero" },
  { id: 110, playerName: "Daniel Muñoz", country: "Colombia", cardType: "Hero" },
  { id: 111, playerName: "Yerry Mina", country: "Colombia", cardType: "Hero" },
  { id: 112, playerName: "Dávinson Sánchez", country: "Colombia", cardType: "Hero" },
  { id: 113, playerName: "Wilmar Barrios", country: "Colombia", cardType: "Hero" },
  { id: 114, playerName: "Richard Ríos", country: "Colombia", cardType: "Hero" },
  { id: 115, playerName: "Jhon Córdoba", country: "Colombia", cardType: "Hero" },
  { id: 116, playerName: "Rafael Santos Borré", country: "Colombia", cardType: "Hero" },
  { id: 117, playerName: "Falcao García", country: "Colombia", cardType: "Hero" },

  // ── Croatia (118–129) ─────────────────────────────────────
  { id: 118,    playerName: "Ivan Perišić",  country: "Croatia", cardType: "Fan Favourite" },
  { id: 119,  playerName: "Team Logo", country: "Croatia", cardType: "Team Logo" },
  { id: 120,  playerName: "Luka Modrić", country: "Croatia", cardType: "Icon" },
  { id: 121, playerName: "Dominik Livaković", country: "Croatia", cardType: "Hero" },
  { id: 122, playerName: "Josip Juranović", country: "Croatia", cardType: "Hero" },
  { id: 123, playerName: "Joško Gvardiol", country: "Croatia", cardType: "Hero" },
  { id: 124, playerName: "Dejan Lovren", country: "Croatia", cardType: "Hero" },
  { id: 125, playerName: "Mateo Kovačić", country: "Croatia", cardType: "Hero" },
  { id: 126, playerName: "Marcelo Brozović", country: "Croatia", cardType: "Hero" },
  { id: 127, playerName: "Nikola Vlašić", country: "Croatia", cardType: "Hero" },
  { id: 128, playerName: "Andrej Kramarić", country: "Croatia", cardType: "Hero" },
  { id: 129, playerName: "Bruno Petković", country: "Croatia", cardType: "Hero" },

  // ── Curaçao (130–141) ─────────────────────────────────────
  { id: 130,    playerName: "Leandro Bacuna",  country: "Curaçao", cardType: "Fan Favourite" },
  { id: 131,  playerName: "Team Logo", country: "Curaçao", cardType: "Team Logo" },
  { id: 132,  playerName: "Cuco Martina", country: "Curaçao", cardType: "Icon" },
  { id: 133, playerName: "Eloy Room", country: "Curaçao", cardType: "Hero" },
  { id: 134, playerName: "Ethan Adenstedt", country: "Curaçao", cardType: "Hero" },
  { id: 135, playerName: "Darryl Lachman", country: "Curaçao", cardType: "Hero" },
  { id: 136, playerName: "Juninho Bacuna", country: "Curaçao", cardType: "Hero" },
  { id: 137, playerName: "Gilson Tavares", country: "Curaçao", cardType: "Hero" },
  { id: 138, playerName: "Rangelo Janga", country: "Curaçao", cardType: "Hero" },
  { id: 139, playerName: "Damil Dankerlui", country: "Curaçao", cardType: "Hero" },
  { id: 140, playerName: "Riechedly Bazoer", country: "Curaçao", cardType: "Hero" },
  { id: 141, playerName: "Anselmo García", country: "Curaçao", cardType: "Hero" },

  // ── Ecuador (142–153) ─────────────────────────────────────
  { id: 142,    playerName: "Enner Valencia",  country: "Ecuador", cardType: "Fan Favourite" },
  { id: 143,  playerName: "Team Logo", country: "Ecuador", cardType: "Team Logo" },
  { id: 144,  playerName: "Moisés Caicedo", country: "Ecuador", cardType: "Icon" },
  { id: 145, playerName: "Hernán Galíndez", country: "Ecuador", cardType: "Hero" },
  { id: 146, playerName: "Piero Hincapié", country: "Ecuador", cardType: "Hero" },
  { id: 147, playerName: "Félix Torres", country: "Ecuador", cardType: "Hero" },
  { id: 148, playerName: "Robert Arboleda", country: "Ecuador", cardType: "Hero" },
  { id: 149, playerName: "Angelo Preciado", country: "Ecuador", cardType: "Hero" },
  { id: 150, playerName: "Carlos Gruezo", country: "Ecuador", cardType: "Hero" },
  { id: 151, playerName: "Jeremy Sarmiento", country: "Ecuador", cardType: "Hero" },
  { id: 152, playerName: "Michael Estrada", country: "Ecuador", cardType: "Hero" },
  { id: 153, playerName: "Kevin Rodríguez", country: "Ecuador", cardType: "Hero" },

  // ── Egypt (154–165) ───────────────────────────────────────
  { id: 154,    playerName: "Mohamed Salah",  country: "Egypt", cardType: "Fan Favourite" },
  { id: 155,  playerName: "Team Logo", country: "Egypt", cardType: "Team Logo" },
  { id: 156,  playerName: "Ahmed El-Shenawy", country: "Egypt", cardType: "Icon" },
  { id: 157, playerName: "Mohamed Abou Gabal", country: "Egypt", cardType: "Hero" },
  { id: 158, playerName: "Ahmed Hegazi", country: "Egypt", cardType: "Hero" },
  { id: 159, playerName: "Omar Kamal", country: "Egypt", cardType: "Hero" },
  { id: 160, playerName: "Mostafa Mohamed", country: "Egypt", cardType: "Hero" },
  { id: 161, playerName: "Amr El-Soula", country: "Egypt", cardType: "Hero" },
  { id: 162, playerName: "Emam Ashour", country: "Egypt", cardType: "Hero" },
  { id: 163, playerName: "Akram Tawfik", country: "Egypt", cardType: "Hero" },
  { id: 164, playerName: "Mahmoud Trezeguet", country: "Egypt", cardType: "Hero" },
  { id: 165, playerName: "Omar Marmoush", country: "Egypt", cardType: "Hero" },

  // ── England (166–177) ─────────────────────────────────────
  { id: 166,    playerName: "Harry Kane",  country: "England", cardType: "Fan Favourite" },
  { id: 167,  playerName: "Team Logo", country: "England", cardType: "Team Logo" },
  { id: 168,  playerName: "Jude Bellingham", country: "England", cardType: "Icon" },
  { id: 169, playerName: "Jordan Pickford", country: "England", cardType: "Hero" },
  { id: 170, playerName: "Kyle Walker", country: "England", cardType: "Hero" },
  { id: 171, playerName: "John Stones", country: "England", cardType: "Hero" },
  { id: 172, playerName: "Marc Guéhi", country: "England", cardType: "Hero" },
  { id: 173, playerName: "Declan Rice", country: "England", cardType: "Hero" },
  { id: 174, playerName: "Phil Foden", country: "England", cardType: "Hero" },
  { id: 175, playerName: "Bukayo Saka", country: "England", cardType: "Hero" },
  { id: 176, playerName: "Marcus Rashford", country: "England", cardType: "Hero" },
  { id: 177, playerName: "Cole Palmer", country: "England", cardType: "Hero" },

  // ── France (178–189) ──────────────────────────────────────
  { id: 178,    playerName: "Kylian Mbappé",  country: "France", cardType: "Fan Favourite" },
  { id: 179,  playerName: "Team Logo", country: "France", cardType: "Team Logo" },
  { id: 180,  playerName: "Antoine Griezmann", country: "France", cardType: "Icon" },
  { id: 181, playerName: "Mike Maignan", country: "France", cardType: "Hero" },
  { id: 182, playerName: "Benjamin Pavard", country: "France", cardType: "Hero" },
  { id: 183, playerName: "Raphaël Varane", country: "France", cardType: "Hero" },
  { id: 184, playerName: "Ibrahima Konaté", country: "France", cardType: "Hero" },
  { id: 185, playerName: "Aurélien Tchouaméni", country: "France", cardType: "Hero" },
  { id: 186, playerName: "N'Golo Kanté", country: "France", cardType: "Hero" },
  { id: 187, playerName: "Eduardo Camavinga", country: "France", cardType: "Hero" },
  { id: 188, playerName: "Ousmane Dembélé", country: "France", cardType: "Hero" },
  { id: 189, playerName: "Marcus Thuram", country: "France", cardType: "Hero" },

  // ── Germany (190–201) ─────────────────────────────────────
  { id: 190,    playerName: "Thomas Müller",  country: "Germany", cardType: "Fan Favourite" },
  { id: 191,  playerName: "Team Logo", country: "Germany", cardType: "Team Logo" },
  { id: 192,  playerName: "Florian Wirtz", country: "Germany", cardType: "Icon" },
  { id: 193, playerName: "Manuel Neuer", country: "Germany", cardType: "Hero" },
  { id: 194, playerName: "Joshua Kimmich", country: "Germany", cardType: "Hero" },
  { id: 195, playerName: "Antonio Rüdiger", country: "Germany", cardType: "Hero" },
  { id: 196, playerName: "Niklas Süle", country: "Germany", cardType: "Hero" },
  { id: 197, playerName: "Toni Kroos", country: "Germany", cardType: "Hero" },
  { id: 198, playerName: "Ilkay Gündogan", country: "Germany", cardType: "Hero" },
  { id: 199, playerName: "Kai Havertz", country: "Germany", cardType: "Hero" },
  { id: 200, playerName: "Leroy Sané", country: "Germany", cardType: "Hero" },
  { id: 201, playerName: "Jamal Musiala", country: "Germany", cardType: "Hero" },

  // ── Ghana (202–213) ───────────────────────────────────────
  { id: 202,    playerName: "André Ayew",  country: "Ghana", cardType: "Fan Favourite" },
  { id: 203,  playerName: "Team Logo", country: "Ghana", cardType: "Team Logo" },
  { id: 204,  playerName: "Thomas Partey", country: "Ghana", cardType: "Icon" },
  { id: 205, playerName: "Lawrence Ati-Zigi", country: "Ghana", cardType: "Hero" },
  { id: 206, playerName: "Daniel Amartey", country: "Ghana", cardType: "Hero" },
  { id: 207, playerName: "Alexander Djiku", country: "Ghana", cardType: "Hero" },
  { id: 208, playerName: "Tariq Lamptey", country: "Ghana", cardType: "Hero" },
  { id: 209, playerName: "Baba Rahman", country: "Ghana", cardType: "Hero" },
  { id: 210, playerName: "Jordan Ayew", country: "Ghana", cardType: "Hero" },
  { id: 211, playerName: "Mohammed Kudus", country: "Ghana", cardType: "Hero" },
  { id: 212, playerName: "Antoine Semenyo", country: "Ghana", cardType: "Hero" },
  { id: 213, playerName: "Iñaki Williams", country: "Ghana", cardType: "Hero" },

  // ── Haiti (214–225) ───────────────────────────────────────
  { id: 214,    playerName: "Duckens Nazon",  country: "Haiti", cardType: "Fan Favourite" },
  { id: 215,  playerName: "Team Logo", country: "Haiti", cardType: "Team Logo" },
  { id: 216,  playerName: "Mechack Jérôme", country: "Haiti", cardType: "Icon" },
  { id: 217, playerName: "Derrick Étienne Jr.", country: "Haiti", cardType: "Hero" },
  { id: 218, playerName: "Steeven Saba", country: "Haiti", cardType: "Hero" },
  { id: 219, playerName: "James Léandre", country: "Haiti", cardType: "Hero" },
  { id: 220, playerName: "Loïck Landre", country: "Haiti", cardType: "Hero" },
  { id: 221, playerName: "Frantzdy Pierrot", country: "Haiti", cardType: "Hero" },
  { id: 222, playerName: "Samuel Piette", country: "Haiti", cardType: "Hero" },
  { id: 223, playerName: "Dénissinho Léandre", country: "Haiti", cardType: "Hero" },
  { id: 224, playerName: "Jean-Vilson Lambert", country: "Haiti", cardType: "Hero" },
  { id: 225, playerName: "Roberto Lépicier", country: "Haiti", cardType: "Hero" },

  // ── Iran (226–237) ────────────────────────────────────────
  { id: 226,    playerName: "Mehdi Taremi",  country: "Iran", cardType: "Fan Favourite" },
  { id: 227,  playerName: "Team Logo", country: "Iran", cardType: "Team Logo" },
  { id: 228,  playerName: "Alireza Jahanbakhsh", country: "Iran", cardType: "Icon" },
  { id: 229, playerName: "Alireza Beiranvand", country: "Iran", cardType: "Hero" },
  { id: 230, playerName: "Shoja Khalilzadeh", country: "Iran", cardType: "Hero" },
  { id: 231, playerName: "Morteza Pouraliganji", country: "Iran", cardType: "Hero" },
  { id: 232, playerName: "Majid Hosseini", country: "Iran", cardType: "Hero" },
  { id: 233, playerName: "Ahmad Noorollahi", country: "Iran", cardType: "Hero" },
  { id: 234, playerName: "Saeid Ezatolahi", country: "Iran", cardType: "Hero" },
  { id: 235, playerName: "Ali Gholizadeh", country: "Iran", cardType: "Hero" },
  { id: 236, playerName: "Sardar Azmoun", country: "Iran", cardType: "Hero" },
  { id: 237, playerName: "Karim Ansarifard", country: "Iran", cardType: "Hero" },

  // ── Ivory Coast (238–249) ─────────────────────────────────
  { id: 238,    playerName: "Sébastien Haller",  country: "Ivory Coast", cardType: "Fan Favourite" },
  { id: 239,  playerName: "Team Logo", country: "Ivory Coast", cardType: "Team Logo" },
  { id: 240,  playerName: "Franck Kessié", country: "Ivory Coast", cardType: "Icon" },
  { id: 241, playerName: "Nicolas Pépé", country: "Ivory Coast", cardType: "Hero" },
  { id: 242, playerName: "Simon Adingra", country: "Ivory Coast", cardType: "Hero" },
  { id: 243, playerName: "Wilfried Zaha", country: "Ivory Coast", cardType: "Hero" },
  { id: 244, playerName: "Serge Aurier", country: "Ivory Coast", cardType: "Hero" },
  { id: 245, playerName: "Jean Michaël Seri", country: "Ivory Coast", cardType: "Hero" },
  { id: 246, playerName: "Cheick Doucouré", country: "Ivory Coast", cardType: "Hero" },
  { id: 247, playerName: "Ibrahim Sangaré", country: "Ivory Coast", cardType: "Hero" },
  { id: 248, playerName: "Max-Alain Gradel", country: "Ivory Coast", cardType: "Hero" },
  { id: 249, playerName: "Odilon Kossounou", country: "Ivory Coast", cardType: "Hero" },

  // ── Japan (250–261) ───────────────────────────────────────
  { id: 250,    playerName: "Takumi Minamino",  country: "Japan", cardType: "Fan Favourite" },
  { id: 251,  playerName: "Team Logo", country: "Japan", cardType: "Team Logo" },
  { id: 252,  playerName: "Takefusa Kubo", country: "Japan", cardType: "Icon" },
  { id: 253, playerName: "Shuichi Gonda", country: "Japan", cardType: "Hero" },
  { id: 254, playerName: "Hiroki Sakai", country: "Japan", cardType: "Hero" },
  { id: 255, playerName: "Maya Yoshida", country: "Japan", cardType: "Hero" },
  { id: 256, playerName: "Ko Itakura", country: "Japan", cardType: "Hero" },
  { id: 257, playerName: "Wataru Endo", country: "Japan", cardType: "Hero" },
  { id: 258, playerName: "Hidemasa Morita", country: "Japan", cardType: "Hero" },
  { id: 259, playerName: "Junya Ito", country: "Japan", cardType: "Hero" },
  { id: 260, playerName: "Ritsu Doan", country: "Japan", cardType: "Hero" },
  { id: 261, playerName: "Daichi Kamada", country: "Japan", cardType: "Hero" },

  // ── Jordan (262–273) ──────────────────────────────────────
  { id: 262,    playerName: "Musa Al-Taamari",  country: "Jordan", cardType: "Fan Favourite" },
  { id: 263,  playerName: "Team Logo", country: "Jordan", cardType: "Team Logo" },
  { id: 264,  playerName: "Yazan Al-Naimat", country: "Jordan", cardType: "Icon" },
  { id: 265, playerName: "Moath Al-Deeb", country: "Jordan", cardType: "Hero" },
  { id: 266, playerName: "Ehsan Haddad", country: "Jordan", cardType: "Hero" },
  { id: 267, playerName: "Mahmoud Al-Mardi", country: "Jordan", cardType: "Hero" },
  { id: 268, playerName: "Ahmad Ghandour", country: "Jordan", cardType: "Hero" },
  { id: 269, playerName: "Baha' Aldin", country: "Jordan", cardType: "Hero" },
  { id: 270, playerName: "Saleh Chikateer", country: "Jordan", cardType: "Hero" },
  { id: 271, playerName: "Rami Hamdan", country: "Jordan", cardType: "Hero" },
  { id: 272, playerName: "Rasmi Kakhia", country: "Jordan", cardType: "Hero" },
  { id: 273, playerName: "Ali Al-Saedi", country: "Jordan", cardType: "Hero" },

  // ── Korea Republic (274–285) ──────────────────────────────
  { id: 274,    playerName: "Son Heung-Min",  country: "Korea Republic", cardType: "Fan Favourite" },
  { id: 275,  playerName: "Team Logo", country: "Korea Republic", cardType: "Team Logo" },
  { id: 276,  playerName: "Kim Min-Jae", country: "Korea Republic", cardType: "Icon" },
  { id: 277, playerName: "Kim Seung-Gyu", country: "Korea Republic", cardType: "Hero" },
  { id: 278, playerName: "Kim Young-Gwon", country: "Korea Republic", cardType: "Hero" },
  { id: 279, playerName: "Lee Ki-Je", country: "Korea Republic", cardType: "Hero" },
  { id: 280, playerName: "Jung Woo-Young", country: "Korea Republic", cardType: "Hero" },
  { id: 281, playerName: "Lee Jae-Sung", country: "Korea Republic", cardType: "Hero" },
  { id: 282, playerName: "Hwang In-Beom", country: "Korea Republic", cardType: "Hero" },
  { id: 283, playerName: "Cho Gue-Sung", country: "Korea Republic", cardType: "Hero" },
  { id: 284, playerName: "Lee Kang-In", country: "Korea Republic", cardType: "Hero" },
  { id: 285, playerName: "Hwang Hee-Chan", country: "Korea Republic", cardType: "Hero" },

  // ── Mexico (286–297) ──────────────────────────────────────
  { id: 286,    playerName: "Hirving Lozano",  country: "Mexico", cardType: "Fan Favourite" },
  { id: 287,  playerName: "Team Logo", country: "Mexico", cardType: "Team Logo" },
  { id: 288,  playerName: "Guillermo Ochoa", country: "Mexico", cardType: "Icon" },
  { id: 289, playerName: "Kevin Álvarez", country: "Mexico", cardType: "Hero" },
  { id: 290, playerName: "César Montes", country: "Mexico", cardType: "Hero" },
  { id: 291, playerName: "Héctor Moreno", country: "Mexico", cardType: "Hero" },
  { id: 292, playerName: "Jesús Gallardo", country: "Mexico", cardType: "Hero" },
  { id: 293, playerName: "Edson Álvarez", country: "Mexico", cardType: "Hero" },
  { id: 294, playerName: "Andrés Guardado", country: "Mexico", cardType: "Hero" },
  { id: 295, playerName: "Alexis Vega", country: "Mexico", cardType: "Hero" },
  { id: 296, playerName: "Roberto Alvarado", country: "Mexico", cardType: "Hero" },
  { id: 297, playerName: "Raúl Jiménez", country: "Mexico", cardType: "Hero" },

  // ── Morocco (298–309) ─────────────────────────────────────
  { id: 298,    playerName: "Achraf Hakimi",  country: "Morocco", cardType: "Fan Favourite" },
  { id: 299,  playerName: "Team Logo", country: "Morocco", cardType: "Team Logo" },
  { id: 300,  playerName: "Youssef En-Nesyri", country: "Morocco", cardType: "Icon" },
  { id: 301, playerName: "Yassine Bounou", country: "Morocco", cardType: "Hero" },
  { id: 302, playerName: "Nayef Aguerd", country: "Morocco", cardType: "Hero" },
  { id: 303, playerName: "Romain Saïss", country: "Morocco", cardType: "Hero" },
  { id: 304, playerName: "Noussair Mazraoui", country: "Morocco", cardType: "Hero" },
  { id: 305, playerName: "Sofyan Amrabat", country: "Morocco", cardType: "Hero" },
  { id: 306, playerName: "Azzedine Ounahi", country: "Morocco", cardType: "Hero" },
  { id: 307, playerName: "Hakim Ziyech", country: "Morocco", cardType: "Hero" },
  { id: 308, playerName: "Soufiane Boufal", country: "Morocco", cardType: "Hero" },
  { id: 309, playerName: "Walid Cheddira", country: "Morocco", cardType: "Hero" },

  // ── Netherlands (310–321) ─────────────────────────────────
  { id: 310,    playerName: "Frenkie de Jong",  country: "Netherlands", cardType: "Fan Favourite" },
  { id: 311,  playerName: "Team Logo", country: "Netherlands", cardType: "Team Logo" },
  { id: 312,  playerName: "Virgil van Dijk", country: "Netherlands", cardType: "Icon" },
  { id: 313, playerName: "Andries Noppert", country: "Netherlands", cardType: "Hero" },
  { id: 314, playerName: "Denzel Dumfries", country: "Netherlands", cardType: "Hero" },
  { id: 315, playerName: "Nathan Aké", country: "Netherlands", cardType: "Hero" },
  { id: 316, playerName: "Stefan de Vrij", country: "Netherlands", cardType: "Hero" },
  { id: 317, playerName: "Daley Blind", country: "Netherlands", cardType: "Hero" },
  { id: 318, playerName: "Xavi Simons", country: "Netherlands", cardType: "Hero" },
  { id: 319, playerName: "Tijjani Reijnders", country: "Netherlands", cardType: "Hero" },
  { id: 320, playerName: "Memphis Depay", country: "Netherlands", cardType: "Hero" },
  { id: 321, playerName: "Cody Gakpo", country: "Netherlands", cardType: "Hero" },

  // ── New Zealand (322–333) ─────────────────────────────────
  { id: 322,    playerName: "Chris Wood",  country: "New Zealand", cardType: "Fan Favourite" },
  { id: 323,  playerName: "Team Logo", country: "New Zealand", cardType: "Team Logo" },
  { id: 324,  playerName: "Bill Tuilagi", country: "New Zealand", cardType: "Icon" },
  { id: 325, playerName: "Stefan Marinovic", country: "New Zealand", cardType: "Hero" },
  { id: 326, playerName: "Liberato Cacace", country: "New Zealand", cardType: "Hero" },
  { id: 327, playerName: "Winston Reid", country: "New Zealand", cardType: "Hero" },
  { id: 328, playerName: "Tommy Smith", country: "New Zealand", cardType: "Hero" },
  { id: 329, playerName: "Joe Bell", country: "New Zealand", cardType: "Hero" },
  { id: 330, playerName: "Clayton Lewis", country: "New Zealand", cardType: "Hero" },
  { id: 331, playerName: "Ryan Thomas", country: "New Zealand", cardType: "Hero" },
  { id: 332, playerName: "Elijah Just", country: "New Zealand", cardType: "Hero" },
  { id: 333, playerName: "Callan Elliot", country: "New Zealand", cardType: "Hero" },

  // ── Norway (334–345) ──────────────────────────────────────
  { id: 334,    playerName: "Martin Ødegaard",  country: "Norway", cardType: "Fan Favourite" },
  { id: 335,  playerName: "Team Logo", country: "Norway", cardType: "Team Logo" },
  { id: 336,  playerName: "Erling Haaland", country: "Norway", cardType: "Icon" },
  { id: 337, playerName: "Alexander Sørloth", country: "Norway", cardType: "Hero" },
  { id: 338, playerName: "Antonio Nusa", country: "Norway", cardType: "Hero" },
  { id: 339, playerName: "Mohamed Elyounoussi", country: "Norway", cardType: "Hero" },
  { id: 340, playerName: "Sander Berge", country: "Norway", cardType: "Hero" },
  { id: 341, playerName: "Kristian Thorstvedt", country: "Norway", cardType: "Hero" },
  { id: 342, playerName: "Leo Østigård", country: "Norway", cardType: "Hero" },
  { id: 343, playerName: "Sigurd Rosted", country: "Norway", cardType: "Hero" },
  { id: 344, playerName: "Morten Thorsby", country: "Norway", cardType: "Hero" },
  { id: 345, playerName: "Ola Solbakken", country: "Norway", cardType: "Hero" },

  // ── Panama (346–357) ──────────────────────────────────────
  { id: 346,    playerName: "Adalberto Carrasquilla",  country: "Panama", cardType: "Fan Favourite" },
  { id: 347,  playerName: "Team Logo", country: "Panama", cardType: "Team Logo" },
  { id: 348,  playerName: "Rolando Blackburn", country: "Panama", cardType: "Icon" },
  { id: 349, playerName: "Luis Mejía", country: "Panama", cardType: "Hero" },
  { id: 350, playerName: "Fidel Escobar", country: "Panama", cardType: "Hero" },
  { id: 351, playerName: "Roderick Miller", country: "Panama", cardType: "Hero" },
  { id: 352, playerName: "Éric Davis", country: "Panama", cardType: "Hero" },
  { id: 353, playerName: "César Yanis", country: "Panama", cardType: "Hero" },
  { id: 354, playerName: "Andrés Andrade", country: "Panama", cardType: "Hero" },
  { id: 355, playerName: "Édgar Barcenas", country: "Panama", cardType: "Hero" },
  { id: 356, playerName: "Julio Dely Valdés Jr.", country: "Panama", cardType: "Hero" },
  { id: 357, playerName: "Ismael Díaz", country: "Panama", cardType: "Hero" },

  // ── Paraguay (358–369) ────────────────────────────────────
  { id: 358,    playerName: "Miguel Almirón",  country: "Paraguay", cardType: "Fan Favourite" },
  { id: 359,  playerName: "Team Logo", country: "Paraguay", cardType: "Team Logo" },
  { id: 360,  playerName: "Gustavo Gómez", country: "Paraguay", cardType: "Icon" },
  { id: 361, playerName: "Antony Silva", country: "Paraguay", cardType: "Hero" },
  { id: 362, playerName: "Robert Rojas", country: "Paraguay", cardType: "Hero" },
  { id: 363, playerName: "Junior Alonso", country: "Paraguay", cardType: "Hero" },
  { id: 364, playerName: "Júnior Ortiz", country: "Paraguay", cardType: "Hero" },
  { id: 365, playerName: "Matías Villasanti", country: "Paraguay", cardType: "Hero" },
  { id: 366, playerName: "Andrés Cubas", country: "Paraguay", cardType: "Hero" },
  { id: 367, playerName: "Jorge Morel", country: "Paraguay", cardType: "Hero" },
  { id: 368, playerName: "Antonio Sanabria", country: "Paraguay", cardType: "Hero" },
  { id: 369, playerName: "Ángel Romero", country: "Paraguay", cardType: "Hero" },

  // ── Portugal (370–381) ────────────────────────────────────
  { id: 370,    playerName: "Cristiano Ronaldo",  country: "Portugal", cardType: "Fan Favourite" },
  { id: 371,  playerName: "Team Logo", country: "Portugal", cardType: "Team Logo" },
  { id: 372,  playerName: "Bernardo Silva", country: "Portugal", cardType: "Icon" },
  { id: 373, playerName: "Rui Patrício", country: "Portugal", cardType: "Hero" },
  { id: 374, playerName: "João Cancelo", country: "Portugal", cardType: "Hero" },
  { id: 375, playerName: "Rúben Dias", country: "Portugal", cardType: "Hero" },
  { id: 376, playerName: "Pepe", country: "Portugal", cardType: "Hero" },
  { id: 377, playerName: "Vitinha", country: "Portugal", cardType: "Hero" },
  { id: 378, playerName: "Bruno Fernandes", country: "Portugal", cardType: "Hero" },
  { id: 379, playerName: "João Félix", country: "Portugal", cardType: "Hero" },
  { id: 380, playerName: "Rafael Leão", country: "Portugal", cardType: "Hero" },
  { id: 381, playerName: "Gonçalo Ramos", country: "Portugal", cardType: "Hero" },

  // ── Qatar (382–393) ───────────────────────────────────────
  { id: 382,    playerName: "Akram Afif",  country: "Qatar", cardType: "Fan Favourite" },
  { id: 383,  playerName: "Team Logo", country: "Qatar", cardType: "Team Logo" },
  { id: 384,  playerName: "Hassan Al-Haydos", country: "Qatar", cardType: "Icon" },
  { id: 385, playerName: "Meshaal Barsham", country: "Qatar", cardType: "Hero" },
  { id: 386, playerName: "Pedro Miguel", country: "Qatar", cardType: "Hero" },
  { id: 387, playerName: "Bassam Al-Rawi", country: "Qatar", cardType: "Hero" },
  { id: 388, playerName: "Tarek Salman", country: "Qatar", cardType: "Hero" },
  { id: 389, playerName: "Karim Boudiaf", country: "Qatar", cardType: "Hero" },
  { id: 390, playerName: "Abdulaziz Hatem", country: "Qatar", cardType: "Hero" },
  { id: 391, playerName: "Ismail Mohamad", country: "Qatar", cardType: "Hero" },
  { id: 392, playerName: "Almoez Ali", country: "Qatar", cardType: "Hero" },
  { id: 393, playerName: "Mohammed Muntari", country: "Qatar", cardType: "Hero" },

  // ── Saudi Arabia (394–405) ────────────────────────────────
  { id: 394,    playerName: "Salem Al-Dawsari",  country: "Saudi Arabia", cardType: "Fan Favourite" },
  { id: 395,  playerName: "Team Logo", country: "Saudi Arabia", cardType: "Team Logo" },
  { id: 396,  playerName: "Mohammed Al-Owais", country: "Saudi Arabia", cardType: "Icon" },
  { id: 397, playerName: "Yasser Al-Shahrani", country: "Saudi Arabia", cardType: "Hero" },
  { id: 398, playerName: "Ali Al-Bulaihi", country: "Saudi Arabia", cardType: "Hero" },
  { id: 399, playerName: "Abdulelah Al-Malki", country: "Saudi Arabia", cardType: "Hero" },
  { id: 400, playerName: "Mohamed Kanno", country: "Saudi Arabia", cardType: "Hero" },
  { id: 401, playerName: "Riyadh Sharahili", country: "Saudi Arabia", cardType: "Hero" },
  { id: 402, playerName: "Hattan Bahebri", country: "Saudi Arabia", cardType: "Hero" },
  { id: 403, playerName: "Firas Al-Buraikan", country: "Saudi Arabia", cardType: "Hero" },
  { id: 404, playerName: "Sami Al-Najei", country: "Saudi Arabia", cardType: "Hero" },
  { id: 405, playerName: "Yasir Al-Shahrani", country: "Saudi Arabia", cardType: "Hero" },

  // ── Scotland (406–417) ────────────────────────────────────
  { id: 406,    playerName: "Andy Robertson",  country: "Scotland", cardType: "Fan Favourite" },
  { id: 407,  playerName: "Team Logo", country: "Scotland", cardType: "Team Logo" },
  { id: 408,  playerName: "Scott McTominay", country: "Scotland", cardType: "Icon" },
  { id: 409, playerName: "Stuart Armstrong", country: "Scotland", cardType: "Hero" },
  { id: 410, playerName: "Kieran Tierney", country: "Scotland", cardType: "Hero" },
  { id: 411, playerName: "John McGinn", country: "Scotland", cardType: "Hero" },
  { id: 412, playerName: "Grant Hanley", country: "Scotland", cardType: "Hero" },
  { id: 413, playerName: "Ryan Jack", country: "Scotland", cardType: "Hero" },
  { id: 414, playerName: "Callum McGregor", country: "Scotland", cardType: "Hero" },
  { id: 415, playerName: "Billy Gilmour", country: "Scotland", cardType: "Hero" },
  { id: 416, playerName: "Lawrence Shankland", country: "Scotland", cardType: "Hero" },
  { id: 417, playerName: "Kevin Nisbet", country: "Scotland", cardType: "Hero" },

  // ── Senegal (418–429) ─────────────────────────────────────
  { id: 418,    playerName: "Ismaïla Sarr",  country: "Senegal", cardType: "Fan Favourite" },
  { id: 419,  playerName: "Team Logo", country: "Senegal", cardType: "Team Logo" },
  { id: 420,  playerName: "Sadio Mané", country: "Senegal", cardType: "Icon" },
  { id: 421, playerName: "Édouard Mendy", country: "Senegal", cardType: "Hero" },
  { id: 422, playerName: "Kalidou Koulibaly", country: "Senegal", cardType: "Hero" },
  { id: 423, playerName: "Abdou Diallo", country: "Senegal", cardType: "Hero" },
  { id: 424, playerName: "Youssouf Sabaly", country: "Senegal", cardType: "Hero" },
  { id: 425, playerName: "Nampalys Mendy", country: "Senegal", cardType: "Hero" },
  { id: 426, playerName: "Idrissa Gueye", country: "Senegal", cardType: "Hero" },
  { id: 427, playerName: "Pape Matar Sarr", country: "Senegal", cardType: "Hero" },
  { id: 428, playerName: "Boulaye Dia", country: "Senegal", cardType: "Hero" },
  { id: 429, playerName: "Nicolas Jackson", country: "Senegal", cardType: "Hero" },

  // ── South Africa (430–441) ────────────────────────────────
  { id: 430,    playerName: "Percy Tau",  country: "South Africa", cardType: "Fan Favourite" },
  { id: 431,  playerName: "Team Logo", country: "South Africa", cardType: "Team Logo" },
  { id: 432,  playerName: "Themba Zwane", country: "South Africa", cardType: "Icon" },
  { id: 433, playerName: "Ronwen Williams", country: "South Africa", cardType: "Hero" },
  { id: 434, playerName: "Reeve Frosler", country: "South Africa", cardType: "Hero" },
  { id: 435, playerName: "Sifiso Hlanti", country: "South Africa", cardType: "Hero" },
  { id: 436, playerName: "Mothobi Mvala", country: "South Africa", cardType: "Hero" },
  { id: 437, playerName: "Bryce Moon", country: "South Africa", cardType: "Hero" },
  { id: 438, playerName: "Teboho Mokoena", country: "South Africa", cardType: "Hero" },
  { id: 439, playerName: "Lyle Foster", country: "South Africa", cardType: "Hero" },
  { id: 440, playerName: "Evidence Makgopa", country: "South Africa", cardType: "Hero" },
  { id: 441, playerName: "Bongokuhle Hlongwane", country: "South Africa", cardType: "Hero" },

  // ── Spain (442–453) ───────────────────────────────────────
  { id: 442,    playerName: "Lamine Yamal",  country: "Spain", cardType: "Fan Favourite" },
  { id: 443,  playerName: "Team Logo", country: "Spain", cardType: "Team Logo" },
  { id: 444,  playerName: "Pedri", country: "Spain", cardType: "Icon" },
  { id: 445, playerName: "Unai Simón", country: "Spain", cardType: "Hero" },
  { id: 446, playerName: "Dani Carvajal", country: "Spain", cardType: "Hero" },
  { id: 447, playerName: "Aymeric Laporte", country: "Spain", cardType: "Hero" },
  { id: 448, playerName: "Pau Cubarsí", country: "Spain", cardType: "Hero" },
  { id: 449, playerName: "Alejandro Grimaldo", country: "Spain", cardType: "Hero" },
  { id: 450, playerName: "Rodri", country: "Spain", cardType: "Hero" },
  { id: 451, playerName: "Fabián Ruiz", country: "Spain", cardType: "Hero" },
  { id: 452, playerName: "Nico Williams", country: "Spain", cardType: "Hero" },
  { id: 453, playerName: "Álvaro Morata", country: "Spain", cardType: "Hero" },

  // ── Switzerland (454–465) ─────────────────────────────────
  { id: 454,    playerName: "Granit Xhaka",  country: "Switzerland", cardType: "Fan Favourite" },
  { id: 455,  playerName: "Team Logo", country: "Switzerland", cardType: "Team Logo" },
  { id: 456,  playerName: "Xherdan Shaqiri", country: "Switzerland", cardType: "Icon" },
  { id: 457, playerName: "Yann Sommer", country: "Switzerland", cardType: "Hero" },
  { id: 458, playerName: "Silvan Widmer", country: "Switzerland", cardType: "Hero" },
  { id: 459, playerName: "Manuel Akanji", country: "Switzerland", cardType: "Hero" },
  { id: 460, playerName: "Nico Elvedi", country: "Switzerland", cardType: "Hero" },
  { id: 461, playerName: "Denis Zakaria", country: "Switzerland", cardType: "Hero" },
  { id: 462, playerName: "Remo Freuler", country: "Switzerland", cardType: "Hero" },
  { id: 463, playerName: "Ruben Vargas", country: "Switzerland", cardType: "Hero" },
  { id: 464, playerName: "Noah Okafor", country: "Switzerland", cardType: "Hero" },
  { id: 465, playerName: "Breel Embolo", country: "Switzerland", cardType: "Hero" },

  // ── Tunisia (466–477) ─────────────────────────────────────
  { id: 466,    playerName: "Youssef Msakni",  country: "Tunisia", cardType: "Fan Favourite" },
  { id: 467,  playerName: "Team Logo", country: "Tunisia", cardType: "Team Logo" },
  { id: 468,  playerName: "Hannibal Mejbri", country: "Tunisia", cardType: "Icon" },
  { id: 469, playerName: "Wahbi Khazri", country: "Tunisia", cardType: "Hero" },
  { id: 470, playerName: "Ali Maaloul", country: "Tunisia", cardType: "Hero" },
  { id: 471, playerName: "Montassar Talbi", country: "Tunisia", cardType: "Hero" },
  { id: 472, playerName: "Dylan Bronn", country: "Tunisia", cardType: "Hero" },
  { id: 473, playerName: "Naim Sliti", country: "Tunisia", cardType: "Hero" },
  { id: 474, playerName: "Anis Ben Slimane", country: "Tunisia", cardType: "Hero" },
  { id: 475, playerName: "Hamza Rafia", country: "Tunisia", cardType: "Hero" },
  { id: 476, playerName: "Ellyes Skhiri", country: "Tunisia", cardType: "Hero" },
  { id: 477, playerName: "Mohamed Drager", country: "Tunisia", cardType: "Hero" },

  // ── United States (478–489) ───────────────────────────────
  { id: 478,    playerName: "Christian Pulisic",  country: "United States", cardType: "Fan Favourite" },
  { id: 479,  playerName: "Team Logo", country: "United States", cardType: "Team Logo" },
  { id: 480,  playerName: "Tyler Adams", country: "United States", cardType: "Icon" },
  { id: 481, playerName: "Matt Turner", country: "United States", cardType: "Hero" },
  { id: 482, playerName: "DeAndre Yedlin", country: "United States", cardType: "Hero" },
  { id: 483, playerName: "Walker Zimmerman", country: "United States", cardType: "Hero" },
  { id: 484, playerName: "Miles Robinson", country: "United States", cardType: "Hero" },
  { id: 485, playerName: "Weston McKennie", country: "United States", cardType: "Hero" },
  { id: 486, playerName: "Yunus Musah", country: "United States", cardType: "Hero" },
  { id: 487, playerName: "Gio Reyna", country: "United States", cardType: "Hero" },
  { id: 488, playerName: "Tim Weah", country: "United States", cardType: "Hero" },
  { id: 489, playerName: "Folarin Balogun", country: "United States", cardType: "Hero" },

  // ── Uruguay (490–501) ─────────────────────────────────────
  { id: 490,    playerName: "Darwin Núñez",  country: "Uruguay", cardType: "Fan Favourite" },
  { id: 491,  playerName: "Team Logo", country: "Uruguay", cardType: "Team Logo" },
  { id: 492,  playerName: "Federico Valverde", country: "Uruguay", cardType: "Icon" },
  { id: 493, playerName: "Sergio Rochet", country: "Uruguay", cardType: "Hero" },
  { id: 494, playerName: "Matías Viña", country: "Uruguay", cardType: "Hero" },
  { id: 495, playerName: "José María Giménez", country: "Uruguay", cardType: "Hero" },
  { id: 496, playerName: "Diego Godín", country: "Uruguay", cardType: "Hero" },
  { id: 497, playerName: "Matías Vecino", country: "Uruguay", cardType: "Hero" },
  { id: 498, playerName: "Rodrigo Bentancur", country: "Uruguay", cardType: "Hero" },
  { id: 499, playerName: "Facundo Pellistri", country: "Uruguay", cardType: "Hero" },
  { id: 500, playerName: "Giorgian de Arrascaeta", country: "Uruguay", cardType: "Hero" },
  { id: 501, playerName: "Luis Suárez", country: "Uruguay", cardType: "Hero" },

  // ── Uzbekistan (502–513) ──────────────────────────────────
  { id: 502,    playerName: "Eldor Shomurodov",  country: "Uzbekistan", cardType: "Fan Favourite" },
  { id: 503,  playerName: "Team Logo", country: "Uzbekistan", cardType: "Team Logo" },
  { id: 504,  playerName: "Jaloliddin Masharipov", country: "Uzbekistan", cardType: "Icon" },
  { id: 505, playerName: "Abbosbek Fayzullaev", country: "Uzbekistan", cardType: "Hero" },
  { id: 506, playerName: "Otabek Shukurov", country: "Uzbekistan", cardType: "Hero" },
  { id: 507, playerName: "Khojiakbar Alijonov", country: "Uzbekistan", cardType: "Hero" },
  { id: 508, playerName: "Jasurbek Yakhshiboev", country: "Uzbekistan", cardType: "Hero" },
  { id: 509, playerName: "Bobur Abdixoliqov", country: "Uzbekistan", cardType: "Hero" },
  { id: 510, playerName: "Khurshid Tursunov", country: "Uzbekistan", cardType: "Hero" },
  { id: 511, playerName: "Lochinbek Rashidov", country: "Uzbekistan", cardType: "Hero" },
  { id: 512, playerName: "Temur Musaev", country: "Uzbekistan", cardType: "Hero" },
  { id: 513, playerName: "Shamsiddin Urinboev", country: "Uzbekistan", cardType: "Hero" },

  // ── Contenders (514–549) ──────────────────────────────────────────────
  { id: 514, playerName: "Christian Eriksen", country: "Denmark", cardType: "Contender" },
  { id: 515, playerName: "Kasper Schmeichel", country: "Denmark", cardType: "Contender" },
  { id: 516, playerName: "Pierre-Emile Højbjerg", country: "Denmark", cardType: "Contender" },
  { id: 517, playerName: "Joakim Mæhle", country: "Denmark", cardType: "Contender" },
  { id: 518, playerName: "Rasmus Højlund", country: "Denmark", cardType: "Contender" },
  { id: 519, playerName: "Andreas Christensen", country: "Denmark", cardType: "Contender" },
  { id: 520, playerName: "Gianluigi Donnarumma", country: "Italy", cardType: "Contender" },
  { id: 521, playerName: "Federico Chiesa", country: "Italy", cardType: "Contender" },
  { id: 522, playerName: "Nicolo Barella", country: "Italy", cardType: "Contender" },
  { id: 523, playerName: "Alessandro Bastoni", country: "Italy", cardType: "Contender" },
  { id: 524, playerName: "Lorenzo Pellegrini", country: "Italy", cardType: "Contender" },
  { id: 525, playerName: "Matteo Retegui", country: "Italy", cardType: "Contender" },
  { id: 526, playerName: "Michail Antonio", country: "Jamaica", cardType: "Contender" },
  { id: 527, playerName: "Bobby Decordova-Reid", country: "Jamaica", cardType: "Contender" },
  { id: 528, playerName: "Leon Bailey", country: "Jamaica", cardType: "Contender" },
  { id: 529, playerName: "Kasey Palmer", country: "Jamaica", cardType: "Contender" },
  { id: 530, playerName: "Shamar Nicholson", country: "Jamaica", cardType: "Contender" },
  { id: 531, playerName: "Damion Lowe", country: "Jamaica", cardType: "Contender" },
  { id: 532, playerName: "Robert Lewandowski", country: "Poland", cardType: "Contender" },
  { id: 533, playerName: "Piotr Zieliński", country: "Poland", cardType: "Contender" },
  { id: 534, playerName: "Matty Cash", country: "Poland", cardType: "Contender" },
  { id: 535, playerName: "Wojciech Szczęsny", country: "Poland", cardType: "Contender" },
  { id: 536, playerName: "Sebastian Szymański", country: "Poland", cardType: "Contender" },
  { id: 537, playerName: "Jakub Kiwior", country: "Poland", cardType: "Contender" },
  { id: 538, playerName: "Alexander Isak", country: "Sweden", cardType: "Contender" },
  { id: 539, playerName: "Dejan Kulusevski", country: "Sweden", cardType: "Contender" },
  { id: 540, playerName: "Emil Forsberg", country: "Sweden", cardType: "Contender" },
  { id: 541, playerName: "Victor Lindelöf", country: "Sweden", cardType: "Contender" },
  { id: 542, playerName: "Jens-Lys Cajuste", country: "Sweden", cardType: "Contender" },
  { id: 543, playerName: "Robin Quaison", country: "Sweden", cardType: "Contender" },
  { id: 544, playerName: "Hakan Çalhanoğlu", country: "Turkey", cardType: "Contender" },
  { id: 545, playerName: "Arda Güler", country: "Turkey", cardType: "Contender" },
  { id: 546, playerName: "Kerem Aktürkoğlu", country: "Turkey", cardType: "Contender" },
  { id: 547, playerName: "Cengiz Ünder", country: "Turkey", cardType: "Contender" },
  { id: 548, playerName: "Zeki Çelik", country: "Turkey", cardType: "Contender" },
  { id: 549, playerName: "Semih Kılıçsoy", country: "Turkey", cardType: "Contender" },

  // ── Top Keepers (550–558) ────────────────────────────────────────────────
  { id: 550, playerName: "Manuel Neuer", country: "Germany", cardType: "Top Keeper" },
  { id: 551, playerName: "Thibaut Courtois", country: "Belgium", cardType: "Top Keeper" },
  { id: 552, playerName: "Alisson", country: "Brazil", cardType: "Top Keeper" },
  { id: 553, playerName: "Emiliano Martínez", country: "Argentina", cardType: "Top Keeper" },
  { id: 554, playerName: "Jordan Pickford", country: "England", cardType: "Top Keeper" },
  { id: 555, playerName: "Yann Sommer", country: "Switzerland", cardType: "Top Keeper" },
  { id: 556, playerName: "Mathew Ryan", country: "Australia", cardType: "Top Keeper" },
  { id: 557, playerName: "Mike Maignan", country: "France", cardType: "Top Keeper" },
  { id: 558, playerName: "Guillermo Ochoa", country: "Mexico", cardType: "Top Keeper" },

  // ── Defensive Rocks (559–567) ────────────────────────────────────────────
  { id: 559, playerName: "Virgil van Dijk", country: "Netherlands", cardType: "Defensive Rock" },
  { id: 560, playerName: "Rúben Dias", country: "Portugal", cardType: "Defensive Rock" },
  { id: 561, playerName: "Kim Min-Jae", country: "Korea Republic", cardType: "Defensive Rock" },
  { id: 562, playerName: "Kalidou Koulibaly", country: "Senegal", cardType: "Defensive Rock" },
  { id: 563, playerName: "Cristian Romero", country: "Argentina", cardType: "Defensive Rock" },
  { id: 564, playerName: "Antonio Rüdiger", country: "Germany", cardType: "Defensive Rock" },
  { id: 565, playerName: "Joško Gvardiol", country: "Croatia", cardType: "Defensive Rock" },
  { id: 566, playerName: "Dávinson Sánchez", country: "Colombia", cardType: "Defensive Rock" },
  { id: 567, playerName: "Achraf Hakimi", country: "Morocco", cardType: "Defensive Rock" },

  // ── Midfield Maestros (568–585) ──────────────────────────────────────────
  { id: 568, playerName: "Luka Modrić", country: "Croatia", cardType: "Midfield Maestro" },
  { id: 569, playerName: "N'Golo Kanté", country: "France", cardType: "Midfield Maestro" },
  { id: 570, playerName: "Toni Kroos", country: "Germany", cardType: "Midfield Maestro" },
  { id: 571, playerName: "Rodri", country: "Spain", cardType: "Midfield Maestro" },
  { id: 572, playerName: "Pedri", country: "Spain", cardType: "Midfield Maestro" },
  { id: 573, playerName: "Declan Rice", country: "England", cardType: "Midfield Maestro" },
  { id: 574, playerName: "Jude Bellingham", country: "England", cardType: "Midfield Maestro" },
  { id: 575, playerName: "Kevin De Bruyne", country: "Belgium", cardType: "Midfield Maestro" },
  { id: 576, playerName: "Bruno Fernandes", country: "Portugal", cardType: "Midfield Maestro" },
  { id: 577, playerName: "Casemiro", country: "Brazil", cardType: "Midfield Maestro" },
  { id: 578, playerName: "Frenkie de Jong", country: "Netherlands", cardType: "Midfield Maestro" },
  { id: 579, playerName: "Granit Xhaka", country: "Switzerland", cardType: "Midfield Maestro" },
  { id: 580, playerName: "Moisés Caicedo", country: "Ecuador", cardType: "Midfield Maestro" },
  { id: 581, playerName: "Sofyan Amrabat", country: "Morocco", cardType: "Midfield Maestro" },
  { id: 582, playerName: "Thomas Partey", country: "Ghana", cardType: "Midfield Maestro" },
  { id: 583, playerName: "Enzo Fernández", country: "Argentina", cardType: "Midfield Maestro" },
  { id: 584, playerName: "Wataru Endo", country: "Japan", cardType: "Midfield Maestro" },
  { id: 585, playerName: "Mateo Kovačić", country: "Croatia", cardType: "Midfield Maestro" },

  // ── Goal Machines (586–607) ──────────────────────────────────────────────
  { id: 586, playerName: "Kylian Mbappé", country: "France", cardType: "Goal Machine" },
  { id: 587, playerName: "Harry Kane", country: "England", cardType: "Goal Machine" },
  { id: 588, playerName: "Erling Haaland", country: "Norway", cardType: "Goal Machine" },
  { id: 589, playerName: "Cristiano Ronaldo", country: "Portugal", cardType: "Goal Machine" },
  { id: 590, playerName: "Lionel Messi", country: "Argentina", cardType: "Goal Machine" },
  { id: 591, playerName: "Vinícius Júnior", country: "Brazil", cardType: "Goal Machine" },
  { id: 592, playerName: "Mohamed Salah", country: "Egypt", cardType: "Goal Machine" },
  { id: 593, playerName: "Lamine Yamal", country: "Spain", cardType: "Goal Machine" },
  { id: 594, playerName: "Son Heung-Min", country: "Korea Republic", cardType: "Goal Machine" },
  { id: 595, playerName: "Julián Álvarez", country: "Argentina", cardType: "Goal Machine" },
  { id: 596, playerName: "Raúl Jiménez", country: "Mexico", cardType: "Goal Machine" },
  { id: 597, playerName: "Jonathan David", country: "Canada", cardType: "Goal Machine" },
  { id: 598, playerName: "Raphinha", country: "Brazil", cardType: "Goal Machine" },
  { id: 599, playerName: "Bukayo Saka", country: "England", cardType: "Goal Machine" },
  { id: 600, playerName: "Antoine Griezmann", country: "France", cardType: "Goal Machine" },
  { id: 601, playerName: "Darwin Núñez", country: "Uruguay", cardType: "Goal Machine" },
  { id: 602, playerName: "Mehdi Taremi", country: "Iran", cardType: "Goal Machine" },
  { id: 603, playerName: "Luis Díaz", country: "Colombia", cardType: "Goal Machine" },
  { id: 604, playerName: "Alexander Sørloth", country: "Norway", cardType: "Goal Machine" },
  { id: 605, playerName: "Cody Gakpo", country: "Netherlands", cardType: "Goal Machine" },
  { id: 606, playerName: "Christian Pulisic", country: "United States", cardType: "Goal Machine" },
  { id: 607, playerName: "Inaki Williams", country: "Ghana", cardType: "Goal Machine" },

  // ── Master Rookies (608–623) ─────────────────────────────────────────────
  { id: 608, playerName: "Pedri", country: "Spain", cardType: "Master Rookie" },
  { id: 609, playerName: "Gavi", country: "Spain", cardType: "Master Rookie" },
  { id: 610, playerName: "Lamine Yamal", country: "Spain", cardType: "Master Rookie" },
  { id: 611, playerName: "Jude Bellingham", country: "England", cardType: "Master Rookie" },
  { id: 612, playerName: "Cole Palmer", country: "England", cardType: "Master Rookie" },
  { id: 613, playerName: "Eduardo Camavinga", country: "France", cardType: "Master Rookie" },
  { id: 614, playerName: "Warren Zaïre-Emery", country: "France", cardType: "Master Rookie" },
  { id: 615, playerName: "Florian Wirtz", country: "Germany", cardType: "Master Rookie" },
  { id: 616, playerName: "Jamal Musiala", country: "Germany", cardType: "Master Rookie" },
  { id: 617, playerName: "Giuliano Simeone", country: "Argentina", cardType: "Master Rookie" },
  { id: 618, playerName: "Matheus Cunha", country: "Brazil", cardType: "Master Rookie" },
  { id: 619, playerName: "Joško Gvardiol", country: "Croatia", cardType: "Master Rookie" },
  { id: 620, playerName: "Tijjani Reijnders", country: "Netherlands", cardType: "Master Rookie" },
  { id: 621, playerName: "Xavi Simons", country: "Netherlands", cardType: "Master Rookie" },
  { id: 622, playerName: "Mohammed Kudus", country: "Ghana", cardType: "Master Rookie" },
  { id: 623, playerName: "Piero Hincapié", country: "Ecuador", cardType: "Master Rookie" },

  // ── Trophy / Official Emblem (624) ─────────────────────────────────────────
  { id: 624, playerName: "Trophy — Official Emblem", country: "FIFA", cardType: "Contender" },

  // ── Official Mascots (625–627) ───────────────────────────────────────────
  { id: 625, playerName: "Maple — WC 2026 Mascot", country: "Canada", cardType: "Mascot" },
  { id: 626, playerName: "Clutch — WC 2026 Mascot", country: "United States", cardType: "Mascot" },
  { id: 627, playerName: "Zavu — WC 2026 Mascot", country: "Mexico", cardType: "Mascot" },

  // ── Eternos 22 (628–630) ────────────────────────────────────────────────
  { id: 628, playerName: "Eternos 22 — Lionel Messi", country: "Argentina", cardType: "Contender" },
  { id: 629, playerName: "Eternos 22 — Diego Maradona", country: "Argentina", cardType: "Contender" },
  { id: 630, playerName: "Eternos 22 — Alfredo Di Stéfano", country: "Argentina", cardType: "Contender" },
];

// O(1) lookup map by card id
export const CARDS_BY_ID = Object.fromEntries(CARDS.map(c => [c.id, c]));

// All unique team names sorted alphabetically
export const TEAMS = [...new Set(CARDS.map(c => c.country))].sort();

// Card type enum in canonical display order
export const CARD_TYPES = [
  "Hero",
  "Icon",
  "Fan Favourite",
  "Team Logo",
  "Golden Baller",
  "Contender",
  "Master Rookie",
  "Top Keeper",
  "Defensive Rock",
  "Midfield Maestro",
  "Goal Machine",
  "Mascot",
];